
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.UserScopes.Commands.Update;

public class UpdateUserScopeCommand : IRequest<UpdateUserScopeResponse>  
{
    
	public string? Scope { get; set; } = null!;
	public Guid Id { get; set; }
	public DateTime? Expiration { get; set; }
    
}




