



//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.Persistence.Repositories;
using IdentityServer.Domain.Entities;
namespace IdentityServer.Application.Services.Repositories;

public interface IUserScopeDal : IAsyncRepository<UserScope, Guid>
{
}


