
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.RoleScopes.Queries.GetById;
using IdentityServer.Application.Features.RoleScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.RoleScopes.Handlers.Queries.GetById;

public class GetByIdRoleScopeQueryHandler : IRequestHandler<GetByIdRoleScopeQuery, GetByIdRoleScopeResponse>
{
    private readonly IRoleScopeDal _roleScopeDal;
    private readonly RoleScopeBusinessRules _roleScopeBusinessRules;
    private readonly IMapper _mapper;

    public GetByIdRoleScopeQueryHandler(IMapper mapper, IRoleScopeDal roleScopeDal, RoleScopeBusinessRules roleScopeBusinessRules)
    {
        _mapper = mapper;
        _roleScopeDal = roleScopeDal;
        _roleScopeBusinessRules = roleScopeBusinessRules;
    }

    public async Task<GetByIdRoleScopeResponse> Handle(GetByIdRoleScopeQuery request, CancellationToken cancellationToken)
    {
        
        var data = await _roleScopeDal.GetAsync(w => w.Id == request.Id, cancellationToken : cancellationToken);
            
        _roleScopeBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        return _mapper.Map<GetByIdRoleScopeResponse>(data);
    }
}



