
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Core.Persistence.Models.Responses;
using Core.Persistence.Paging;
using Jumper.Application.Features.EntityPropertyFeatureDefinitions.Commands.BulkCreate;
using Jumper.Application.Features.EntityPropertyFeatureDefinitions.Commands.Create;
using Jumper.Application.Features.EntityPropertyFeatureDefinitions.Commands.Update;
using Jumper.Application.Features.EntityPropertyFeatureDefinitions.Commands.BulkUpdate;
using Jumper.Application.Features.EntityPropertyFeatureDefinitions.Commands.DeleteById;
using Jumper.Application.Features.EntityPropertyFeatureDefinitions.Queries.ListDynamic;
using Jumper.Application.Features.EntityPropertyFeatureDefinitions.Queries.GetById;
using Jumper.Domain.Entities;

namespace Jumper.Application.Features.EntityPropertyFeatureDefinitions.Profiles;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        
		CreateMap<BulkCreateEntityPropertyFeatureDefinitionCommand,EntityPropertyFeatureDefinition>();
		CreateMap<EntityPropertyFeatureDefinition, BulkCreateEntityPropertyFeatureDefinitionResponse>();
		CreateMap<CreateEntityPropertyFeatureDefinitionCommand,EntityPropertyFeatureDefinition>();
		CreateMap<EntityPropertyFeatureDefinition, CreateEntityPropertyFeatureDefinitionResponse>();
		CreateMap<UpdateEntityPropertyFeatureDefinitionCommand,EntityPropertyFeatureDefinition>();
		CreateMap<EntityPropertyFeatureDefinition, UpdateEntityPropertyFeatureDefinitionResponse>();
		CreateMap<BulkUpdateEntityPropertyFeatureDefinitionCommand,EntityPropertyFeatureDefinition>();
		CreateMap<EntityPropertyFeatureDefinition, BulkUpdateEntityPropertyFeatureDefinitionResponse>();
		CreateMap<DeleteByIdEntityPropertyFeatureDefinitionCommand,EntityPropertyFeatureDefinition>();
		CreateMap<EntityPropertyFeatureDefinition, DeleteByIdEntityPropertyFeatureDefinitionResponse>();
		CreateMap<Paginate<EntityPropertyFeatureDefinition>, ListModel<ListDynamicEntityPropertyFeatureDefinitionResponse>>();
		CreateMap<EntityPropertyFeatureDefinition, ListDynamicEntityPropertyFeatureDefinitionResponse>();
		CreateMap<EntityPropertyFeatureDefinition, GetByIdEntityPropertyFeatureDefinitionResponse>();
    }
}




