
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Commands.BulkUpdate;
using Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using MediatR;
namespace Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Handlers.Commands.BulkUpdate;

public class BulkUpdateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationCommandHandler : IRequestHandler<BulkUpdateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationWrapperCommand, List<BulkUpdateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse>>
{
    private readonly IEntityPropertyFeatureDefinitionProjectEntityPropertyRelationDal _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal;
    private readonly EntityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationCommandHandler(IMapper mapper, IEntityPropertyFeatureDefinitionProjectEntityPropertyRelationDal entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal, EntityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules)
    {
        _mapper = mapper;
        _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal = entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal;
        _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules = entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules;
    }

    public async Task<List<BulkUpdateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse>> Handle(BulkUpdateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse>>(datas.Items);
    }
}



