
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

namespace IdentityServer.Application.Features.RoleScopes.Queries.ListDynamic;

public class ListDynamicRoleScopeResponse
{
    
	public DateTime UpdatedTime { get; set; }
	public DateTime? Expiration { get; set; }
	public DateTime DeletedTime { get; set; }
	public DateTime CreatedTime { get; set; }
	public Guid Id { get; set; }
	public string Scope { get; set; }
    
}




