
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ApiResources.Commands.BulkUpdate;
using IdentityServer.Application.Features.ApiResources.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.ApiResources.Handlers.Commands.BulkUpdate;

public class BulkUpdateApiResourceCommandHandler : IRequestHandler<BulkUpdateApiResourceWrapperCommand, List<BulkUpdateApiResourceResponse>>
{
    private readonly IApiResourceDal _apiResourceDal;
    private readonly ApiResourceBusinessRules _apiResourceBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateApiResourceCommandHandler(IMapper mapper, IApiResourceDal apiResourceDal, ApiResourceBusinessRules apiResourceBusinessRules)
    {
        _mapper = mapper;
        _apiResourceDal = apiResourceDal;
        _apiResourceBusinessRules = apiResourceBusinessRules;
    }

    public async Task<List<BulkUpdateApiResourceResponse>> Handle(BulkUpdateApiResourceWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _apiResourceDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        _apiResourceBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _apiResourceDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateApiResourceResponse>>(datas.Items);
    }
}



