
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.Clients.Queries.ListDynamic;
using IdentityServer.Application.Features.Clients.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using Core.Persistence.Models.Responses;
using MediatR;
namespace IdentityServer.Application.Features.Clients.Handlers.Queries.ListDynamic;

public class ListDynamicClientQueryHandler : IRequestHandler<ListDynamicClientQuery, ListModel<ListDynamicClientResponse>>
{
    private readonly IClientDal _clientDal;
    private readonly ClientBusinessRules _clientBusinessRules;
    private readonly IMapper _mapper;

    public ListDynamicClientQueryHandler(IMapper mapper, IClientDal clientDal, ClientBusinessRules clientBusinessRules)
    {
        _mapper = mapper;
        _clientDal = clientDal;
        _clientBusinessRules = clientBusinessRules;
    }

    public async Task<ListModel<ListDynamicClientResponse>> Handle(ListDynamicClientQuery request, CancellationToken cancellationToken)
    {
        var datas = await _clientDal.GetListByDynamicAsync(request.DynamicQuery, size: request.PageRequest.PageSize, index: request.PageRequest.PageIndex, cancellationToken : cancellationToken);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        var returnData = _mapper.Map<ListModel<ListDynamicClientResponse>>(datas);
        _clientBusinessRules.FillDynamicFilter(returnData, request.DynamicQuery, request.PageRequest);
        return returnData;

    }
}



