
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

namespace Jumper.Application.Features.EntityFeatureDefinitions.Commands.DeleteById;

public class DeleteByIdEntityFeatureDefinitionResponse
{
    
	public Guid Id { get; set; }
    
}




