
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ClientUserRelations.Queries.ListDynamic;
using IdentityServer.Application.Features.ClientUserRelations.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using Core.Persistence.Models.Responses;
using MediatR;
namespace IdentityServer.Application.Features.ClientUserRelations.Handlers.Queries.ListDynamic;

public class ListDynamicClientUserRelationQueryHandler : IRequestHandler<ListDynamicClientUserRelationQuery, ListModel<ListDynamicClientUserRelationResponse>>
{
    private readonly IClientUserRelationDal _clientUserRelationDal;
    private readonly ClientUserRelationBusinessRules _clientUserRelationBusinessRules;
    private readonly IMapper _mapper;

    public ListDynamicClientUserRelationQueryHandler(IMapper mapper, IClientUserRelationDal clientUserRelationDal, ClientUserRelationBusinessRules clientUserRelationBusinessRules)
    {
        _mapper = mapper;
        _clientUserRelationDal = clientUserRelationDal;
        _clientUserRelationBusinessRules = clientUserRelationBusinessRules;
    }

    public async Task<ListModel<ListDynamicClientUserRelationResponse>> Handle(ListDynamicClientUserRelationQuery request, CancellationToken cancellationToken)
    {
        var datas = await _clientUserRelationDal.GetListByDynamicAsync(request.DynamicQuery, size: request.PageRequest.PageSize, index: request.PageRequest.PageIndex, cancellationToken : cancellationToken);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        var returnData = _mapper.Map<ListModel<ListDynamicClientUserRelationResponse>>(datas);
        _clientUserRelationBusinessRules.FillDynamicFilter(returnData, request.DynamicQuery, request.PageRequest);
        return returnData;

    }
}



