
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ClientScopes.Commands.BulkUpdate;
using IdentityServer.Application.Features.ClientScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.ClientScopes.Handlers.Commands.BulkUpdate;

public class BulkUpdateClientScopeCommandHandler : IRequestHandler<BulkUpdateClientScopeWrapperCommand, List<BulkUpdateClientScopeResponse>>
{
    private readonly IClientScopeDal _clientScopeDal;
    private readonly ClientScopeBusinessRules _clientScopeBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateClientScopeCommandHandler(IMapper mapper, IClientScopeDal clientScopeDal, ClientScopeBusinessRules clientScopeBusinessRules)
    {
        _mapper = mapper;
        _clientScopeDal = clientScopeDal;
        _clientScopeBusinessRules = clientScopeBusinessRules;
    }

    public async Task<List<BulkUpdateClientScopeResponse>> Handle(BulkUpdateClientScopeWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _clientScopeDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        _clientScopeBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _clientScopeDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateClientScopeResponse>>(datas.Items);
    }
}



