
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.AuthMessageses.Queries.ListDynamic;
using IdentityServer.Application.Features.AuthMessageses.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using Core.Persistence.Models.Responses;
using MediatR;
namespace IdentityServer.Application.Features.AuthMessageses.Handlers.Queries.ListDynamic;

public class ListDynamicAuthMessagesQueryHandler : IRequestHandler<ListDynamicAuthMessagesQuery, ListModel<ListDynamicAuthMessagesResponse>>
{
    private readonly IAuthMessagesDal _authMessagesDal;
    private readonly AuthMessagesBusinessRules _authMessagesBusinessRules;
    private readonly IMapper _mapper;

    public ListDynamicAuthMessagesQueryHandler(IMapper mapper, IAuthMessagesDal authMessagesDal, AuthMessagesBusinessRules authMessagesBusinessRules)
    {
        _mapper = mapper;
        _authMessagesDal = authMessagesDal;
        _authMessagesBusinessRules = authMessagesBusinessRules;
    }

    public async Task<ListModel<ListDynamicAuthMessagesResponse>> Handle(ListDynamicAuthMessagesQuery request, CancellationToken cancellationToken)
    {
        var datas = await _authMessagesDal.GetListByDynamicAsync(request.DynamicQuery, size: request.PageRequest.PageSize, index: request.PageRequest.PageIndex, cancellationToken : cancellationToken);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        var returnData = _mapper.Map<ListModel<ListDynamicAuthMessagesResponse>>(datas);
        _authMessagesBusinessRules.FillDynamicFilter(returnData, request.DynamicQuery, request.PageRequest);
        return returnData;

    }
}



