
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ClientUserRelations.Commands.BulkCreate;
using IdentityServer.Application.Features.ClientUserRelations.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;

using MediatR;
namespace IdentityServer.Application.Features.ClientUserRelations.Handlers.Commands.BulkCreate;

public class BulkCreateClientUserRelationCommandHandler : IRequestHandler<BulkCreateClientUserRelationWrapperCommand, List<BulkCreateClientUserRelationResponse>>
{
    private readonly IClientUserRelationDal _clientUserRelationDal;
    private readonly ClientUserRelationBusinessRules _clientUserRelationBusinessRules;
    private readonly IMapper _mapper;

    public BulkCreateClientUserRelationCommandHandler(IMapper mapper, IClientUserRelationDal clientUserRelationDal, ClientUserRelationBusinessRules clientUserRelationBusinessRules)
    {
        _mapper = mapper;
        _clientUserRelationDal = clientUserRelationDal;
        _clientUserRelationBusinessRules = clientUserRelationBusinessRules;
    }

    public async Task<List<BulkCreateClientUserRelationResponse>> Handle(BulkCreateClientUserRelationWrapperCommand request, CancellationToken cancellationToken)
    {
        var datas = _mapper.Map<List<ClientUserRelation>>(request);

        _clientUserRelationBusinessRules.SetId(datas);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _clientUserRelationDal.AddRangeAsync(datas);

        return _mapper.Map<List<BulkCreateClientUserRelationResponse>>(datas);
    }
}



