
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using Core.Persistence.Repositories;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using Jumper.Persistance.Contexts;
namespace Jumper.Persistence.Repositories;

public class EntityPropertyFeatureDefinitionDal : EfRepositoryBase<EntityPropertyFeatureDefinition, Guid, JumperDbContext>, IEntityPropertyFeatureDefinitionDal
{
    public EntityPropertyFeatureDefinitionDal(JumperDbContext context) : base(context)
    {
    }
}


