
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ClientUserRelations.Commands.Update;
using IdentityServer.Application.Features.ClientUserRelations.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.ClientUserRelations.Handlers.Commands.Update;

public class UpdateClientUserRelationCommandHandler : IRequestHandler<UpdateClientUserRelationCommand, UpdateClientUserRelationResponse>
{
    private readonly IClientUserRelationDal _clientUserRelationDal;
    private readonly ClientUserRelationBusinessRules _clientUserRelationBusinessRules;
    private readonly IMapper _mapper;

    public UpdateClientUserRelationCommandHandler(IMapper mapper, IClientUserRelationDal clientUserRelationDal, ClientUserRelationBusinessRules clientUserRelationBusinessRules)
    {
        _mapper = mapper;
        _clientUserRelationDal = clientUserRelationDal;
        _clientUserRelationBusinessRules = clientUserRelationBusinessRules;
    }

    public async Task<UpdateClientUserRelationResponse> Handle(UpdateClientUserRelationCommand request, CancellationToken cancellationToken)
    {
        var data = await _clientUserRelationDal.GetAsync(w => w.Id == request.Id);

        _clientUserRelationBusinessRules.ThrowExceptionIfDataNull(data);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        _mapper.Map(request, data);
        await _clientUserRelationDal.UpdateAsync(data);

        return _mapper.Map<UpdateClientUserRelationResponse>(data);
    }
}



