



//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.UserScopes.Commands.BulkUpdate;
using IdentityServer.Application.Features.UserScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.UserScopes.Handlers.Commands.BulkUpdate;

public class BulkUpdateUserScopeCommandHandler : IRequestHandler<BulkUpdateUserScopeWrapperCommand, List<BulkUpdateUserScopeResponse>>
{
    private readonly IUserScopeDal _userScopeDal;
    private readonly UserScopeBusinessRules _userScopeBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateUserScopeCommandHandler(IMapper mapper, IUserScopeDal userScopeDal, UserScopeBusinessRules userScopeBusinessRules)
    {
        _mapper = mapper;
        _userScopeDal = userScopeDal;
        _userScopeBusinessRules = userScopeBusinessRules;
    }

    public async Task<List<BulkUpdateUserScopeResponse>> Handle(BulkUpdateUserScopeWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _userScopeDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        _userScopeBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _userScopeDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateUserScopeResponse>>(datas.Items);
    }
}



