
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ApiResourceScopes.Commands.BulkCreate;
using IdentityServer.Application.Features.ApiResourceScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;

using MediatR;
namespace IdentityServer.Application.Features.ApiResourceScopes.Handlers.Commands.BulkCreate;

public class BulkCreateApiResourceScopeCommandHandler : IRequestHandler<BulkCreateApiResourceScopeWrapperCommand, List<BulkCreateApiResourceScopeResponse>>
{
    private readonly IApiResourceScopeDal _apiResourceScopeDal;
    private readonly ApiResourceScopeBusinessRules _apiResourceScopeBusinessRules;
    private readonly IMapper _mapper;

    public BulkCreateApiResourceScopeCommandHandler(IMapper mapper, IApiResourceScopeDal apiResourceScopeDal, ApiResourceScopeBusinessRules apiResourceScopeBusinessRules)
    {
        _mapper = mapper;
        _apiResourceScopeDal = apiResourceScopeDal;
        _apiResourceScopeBusinessRules = apiResourceScopeBusinessRules;
    }

    public async Task<List<BulkCreateApiResourceScopeResponse>> Handle(BulkCreateApiResourceScopeWrapperCommand request, CancellationToken cancellationToken)
    {
        var datas = _mapper.Map<List<ApiResourceScope>>(request);

        _apiResourceScopeBusinessRules.SetId(datas);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _apiResourceScopeDal.AddRangeAsync(datas);

        return _mapper.Map<List<BulkCreateApiResourceScopeResponse>>(datas);
    }
}



