
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ApiResourceClientRelations.Commands.DeleteById;
using IdentityServer.Application.Features.ApiResourceClientRelations.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.ApiResourceClientRelations.Handlers.Commands.DeleteById;

public class DeleteByIdApiResourceClientRelationCommandHandler : IRequestHandler<DeleteByIdApiResourceClientRelationCommand, DeleteByIdApiResourceClientRelationResponse>
{
    private readonly IApiResourceClientRelationDal _apiResourceClientRelationDal;
    private readonly ApiResourceClientRelationBusinessRules _apiResourceClientRelationBusinessRules;
    private readonly IMapper _mapper;

    public DeleteByIdApiResourceClientRelationCommandHandler(IMapper mapper, IApiResourceClientRelationDal apiResourceClientRelationDal, ApiResourceClientRelationBusinessRules apiResourceClientRelationBusinessRules)
    {
        _mapper = mapper;
        _apiResourceClientRelationDal = apiResourceClientRelationDal;
        _apiResourceClientRelationBusinessRules = apiResourceClientRelationBusinessRules;
    }

    public async Task<DeleteByIdApiResourceClientRelationResponse> Handle(DeleteByIdApiResourceClientRelationCommand request, CancellationToken cancellationToken)
    {
        
        var data = await _apiResourceClientRelationDal.GetAsync(w => w.Id == request.Id);
            
        _apiResourceClientRelationBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _apiResourceClientRelationDal.DeleteAsync(data!);

        return _mapper.Map<DeleteByIdApiResourceClientRelationResponse>(data);
    }
}



