
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ApiResourceClientRelations.Queries.ListDynamic;
using IdentityServer.Application.Features.ApiResourceClientRelations.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using Core.Persistence.Models.Responses;
using MediatR;
namespace IdentityServer.Application.Features.ApiResourceClientRelations.Handlers.Queries.ListDynamic;

public class ListDynamicApiResourceClientRelationQueryHandler : IRequestHandler<ListDynamicApiResourceClientRelationQuery, ListModel<ListDynamicApiResourceClientRelationResponse>>
{
    private readonly IApiResourceClientRelationDal _apiResourceClientRelationDal;
    private readonly ApiResourceClientRelationBusinessRules _apiResourceClientRelationBusinessRules;
    private readonly IMapper _mapper;

    public ListDynamicApiResourceClientRelationQueryHandler(IMapper mapper, IApiResourceClientRelationDal apiResourceClientRelationDal, ApiResourceClientRelationBusinessRules apiResourceClientRelationBusinessRules)
    {
        _mapper = mapper;
        _apiResourceClientRelationDal = apiResourceClientRelationDal;
        _apiResourceClientRelationBusinessRules = apiResourceClientRelationBusinessRules;
    }

    public async Task<ListModel<ListDynamicApiResourceClientRelationResponse>> Handle(ListDynamicApiResourceClientRelationQuery request, CancellationToken cancellationToken)
    {
        var datas = await _apiResourceClientRelationDal.GetListByDynamicAsync(request.DynamicQuery, size: request.PageRequest.PageSize, index: request.PageRequest.PageIndex, cancellationToken : cancellationToken);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        var returnData = _mapper.Map<ListModel<ListDynamicApiResourceClientRelationResponse>>(datas);
        _apiResourceClientRelationBusinessRules.FillDynamicFilter(returnData, request.DynamicQuery, request.PageRequest);
        return returnData;

    }
}



