
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.ClientScopes.Commands.BulkUpdate;

public class BulkUpdateClientScopeCommandValidator : AbstractValidator<BulkUpdateClientScopeCommand>
{
    public BulkUpdateClientScopeCommandValidator()
    {
         
		RuleFor(w => w.Scope).NotEmpty().NotNull().WithMessage("Lütfen Scope Alanını Doldurun veya Seçin.");
		RuleFor(w => w.Expiration).NotEmpty().NotNull().WithMessage("Lütfen Expiration Alanını Doldurun veya Seçin.");

        
    }
}





