
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.Update;

public class UpdateEntityFeatureDefinitionProjectEntityRelationCommandValidator : AbstractValidator<UpdateEntityFeatureDefinitionProjectEntityRelationCommand>
{
    public UpdateEntityFeatureDefinitionProjectEntityRelationCommandValidator()
    {
         
		RuleFor(w => w.EntityFeatureDefinitionId).NotEmpty().NotNull().WithMessage("Lütfen EntityFeatureDefinitionId Alanını Doldurun veya Seçin.");
		RuleFor(w => w.ProjectEntityId).NotEmpty().NotNull().WithMessage("Lütfen ProjectEntityId Alanını Doldurun veya Seçin.");

        
    }
}





