
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ApiResourceScopes.Queries.GetById;
using IdentityServer.Application.Features.ApiResourceScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.ApiResourceScopes.Handlers.Queries.GetById;

public class GetByIdApiResourceScopeQueryHandler : IRequestHandler<GetByIdApiResourceScopeQuery, GetByIdApiResourceScopeResponse>
{
    private readonly IApiResourceScopeDal _apiResourceScopeDal;
    private readonly ApiResourceScopeBusinessRules _apiResourceScopeBusinessRules;
    private readonly IMapper _mapper;

    public GetByIdApiResourceScopeQueryHandler(IMapper mapper, IApiResourceScopeDal apiResourceScopeDal, ApiResourceScopeBusinessRules apiResourceScopeBusinessRules)
    {
        _mapper = mapper;
        _apiResourceScopeDal = apiResourceScopeDal;
        _apiResourceScopeBusinessRules = apiResourceScopeBusinessRules;
    }

    public async Task<GetByIdApiResourceScopeResponse> Handle(GetByIdApiResourceScopeQuery request, CancellationToken cancellationToken)
    {
        
        var data = await _apiResourceScopeDal.GetAsync(w => w.Id == request.Id, cancellationToken : cancellationToken);
            
        _apiResourceScopeBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        return _mapper.Map<GetByIdApiResourceScopeResponse>(data);
    }
}



