
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.ClientScopes.Commands.BulkCreate;


public class BulkCreateClientScopeWrapperCommand : IRequest<List<BulkCreateClientScopeResponse>>  
{
    public List<BulkCreateClientScopeCommand> Items { get; set; }
}

public class BulkCreateClientScopeCommand
{
    
	public string Scope { get; set; }
	public Guid Id { get; set; }
	public DateTime Expiration { get; set; }
    
}




