



//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.UserScopes.Commands.DeleteById;
using IdentityServer.Application.Features.UserScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.UserScopes.Handlers.Commands.DeleteById;

public class DeleteByIdUserScopeCommandHandler : IRequestHandler<DeleteByIdUserScopeCommand, DeleteByIdUserScopeResponse>
{
    private readonly IUserScopeDal _userScopeDal;
    private readonly UserScopeBusinessRules _userScopeBusinessRules;
    private readonly IMapper _mapper;

    public DeleteByIdUserScopeCommandHandler(IMapper mapper, IUserScopeDal userScopeDal, UserScopeBusinessRules userScopeBusinessRules)
    {
        _mapper = mapper;
        _userScopeDal = userScopeDal;
        _userScopeBusinessRules = userScopeBusinessRules;
    }

    public async Task<DeleteByIdUserScopeResponse> Handle(DeleteByIdUserScopeCommand request, CancellationToken cancellationToken)
    {
        
        var data = await _userScopeDal.GetAsync(w => w.Id == request.Id);
            
        _userScopeBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _userScopeDal.DeleteAsync(data!);

        return _mapper.Map<DeleteByIdUserScopeResponse>(data);
    }
}



