
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Core.Persistence.Models.Responses;
using Core.Persistence.Paging;
using Jumper.Application.Features.EntityFeatureDefinitions.Commands.BulkCreate;
using Jumper.Application.Features.EntityFeatureDefinitions.Commands.Create;
using Jumper.Application.Features.EntityFeatureDefinitions.Commands.Update;
using Jumper.Application.Features.EntityFeatureDefinitions.Commands.BulkUpdate;
using Jumper.Application.Features.EntityFeatureDefinitions.Commands.DeleteById;
using Jumper.Application.Features.EntityFeatureDefinitions.Queries.ListDynamic;
using Jumper.Application.Features.EntityFeatureDefinitions.Queries.GetById;
using Jumper.Domain.Entities;

namespace Jumper.Application.Features.EntityFeatureDefinitions.Profiles;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        
		CreateMap<BulkCreateEntityFeatureDefinitionCommand,EntityFeatureDefinition>();
		CreateMap<EntityFeatureDefinition, BulkCreateEntityFeatureDefinitionResponse>();
		CreateMap<CreateEntityFeatureDefinitionCommand,EntityFeatureDefinition>();
		CreateMap<EntityFeatureDefinition, CreateEntityFeatureDefinitionResponse>();
		CreateMap<UpdateEntityFeatureDefinitionCommand,EntityFeatureDefinition>();
		CreateMap<EntityFeatureDefinition, UpdateEntityFeatureDefinitionResponse>();
		CreateMap<BulkUpdateEntityFeatureDefinitionCommand,EntityFeatureDefinition>();
		CreateMap<EntityFeatureDefinition, BulkUpdateEntityFeatureDefinitionResponse>();
		CreateMap<DeleteByIdEntityFeatureDefinitionCommand,EntityFeatureDefinition>();
		CreateMap<EntityFeatureDefinition, DeleteByIdEntityFeatureDefinitionResponse>();
		CreateMap<Paginate<EntityFeatureDefinition>, ListModel<ListDynamicEntityFeatureDefinitionResponse>>();
		CreateMap<EntityFeatureDefinition, ListDynamicEntityFeatureDefinitionResponse>();
		CreateMap<EntityFeatureDefinition, GetByIdEntityFeatureDefinitionResponse>();
    }
}




