
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.AuthMessageses.Commands.Create;
using IdentityServer.Application.Features.AuthMessageses.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.AuthMessageses.Handlers.Commands.Create;

public class CreateAuthMessagesCommandHandler : IRequestHandler<CreateAuthMessagesCommand, CreateAuthMessagesResponse>
{
    private readonly IAuthMessagesDal _authMessagesDal;
    private readonly AuthMessagesBusinessRules _authMessagesBusinessRules;
    private readonly IMapper _mapper;

    public CreateAuthMessagesCommandHandler(IMapper mapper, IAuthMessagesDal authMessagesDal, AuthMessagesBusinessRules authMessagesBusinessRules)
    {
        _mapper = mapper;
        _authMessagesDal = authMessagesDal;
        _authMessagesBusinessRules = authMessagesBusinessRules;
    }

    public async Task<CreateAuthMessagesResponse> Handle(CreateAuthMessagesCommand request, CancellationToken cancellationToken)
    {
        var data = _mapper.Map<AuthMessages>(request);

        _authMessagesBusinessRules.SetId(data);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _authMessagesDal.AddAsync(data);

        return _mapper.Map<CreateAuthMessagesResponse>(data);
    }
}



