
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.UserRefreshTokens.Commands.Create;

public class CreateUserRefreshTokenCommandValidator : AbstractValidator<CreateUserRefreshTokenCommand>
{
    public CreateUserRefreshTokenCommandValidator()
    {
         
		RuleFor(w => w.Expiration).NotEmpty().NotNull().WithMessage("Lütfen Expiration Alanını Doldurun veya Seçin.");
		RuleFor(w => w.Code).NotEmpty().NotNull().WithMessage("Lütfen Code Alanını Doldurun veya Seçin.");

        
    }
}





