
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.DeleteById;

public class DeleteByIdEntityFeatureDefinitionProjectEntityRelationCommandValidator : AbstractValidator<DeleteByIdEntityFeatureDefinitionProjectEntityRelationCommand>
{
    public DeleteByIdEntityFeatureDefinitionProjectEntityRelationCommandValidator()
    {
         

        
    }
}





