
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ApiResources.Commands.BulkCreate;
using IdentityServer.Application.Features.ApiResources.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;

using MediatR;
namespace IdentityServer.Application.Features.ApiResources.Handlers.Commands.BulkCreate;

public class BulkCreateApiResourceCommandHandler : IRequestHandler<BulkCreateApiResourceWrapperCommand, List<BulkCreateApiResourceResponse>>
{
    private readonly IApiResourceDal _apiResourceDal;
    private readonly ApiResourceBusinessRules _apiResourceBusinessRules;
    private readonly IMapper _mapper;

    public BulkCreateApiResourceCommandHandler(IMapper mapper, IApiResourceDal apiResourceDal, ApiResourceBusinessRules apiResourceBusinessRules)
    {
        _mapper = mapper;
        _apiResourceDal = apiResourceDal;
        _apiResourceBusinessRules = apiResourceBusinessRules;
    }

    public async Task<List<BulkCreateApiResourceResponse>> Handle(BulkCreateApiResourceWrapperCommand request, CancellationToken cancellationToken)
    {
        var datas = _mapper.Map<List<ApiResource>>(request);

        _apiResourceBusinessRules.SetId(datas);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _apiResourceDal.AddRangeAsync(datas);

        return _mapper.Map<List<BulkCreateApiResourceResponse>>(datas);
    }
}



