
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.UserRefreshTokens.Commands.BulkUpdate;
using IdentityServer.Application.Features.UserRefreshTokens.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.UserRefreshTokens.Handlers.Commands.BulkUpdate;

public class BulkUpdateUserRefreshTokenCommandHandler : IRequestHandler<BulkUpdateUserRefreshTokenWrapperCommand, List<BulkUpdateUserRefreshTokenResponse>>
{
    private readonly IUserRefreshTokenDal _userRefreshTokenDal;
    private readonly UserRefreshTokenBusinessRules _userRefreshTokenBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateUserRefreshTokenCommandHandler(IMapper mapper, IUserRefreshTokenDal userRefreshTokenDal, UserRefreshTokenBusinessRules userRefreshTokenBusinessRules)
    {
        _mapper = mapper;
        _userRefreshTokenDal = userRefreshTokenDal;
        _userRefreshTokenBusinessRules = userRefreshTokenBusinessRules;
    }

    public async Task<List<BulkUpdateUserRefreshTokenResponse>> Handle(BulkUpdateUserRefreshTokenWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _userRefreshTokenDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        _userRefreshTokenBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _userRefreshTokenDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateUserRefreshTokenResponse>>(datas.Items);
    }
}



