
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ApiResourceScopes.Commands.BulkUpdate;
using IdentityServer.Application.Features.ApiResourceScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.ApiResourceScopes.Handlers.Commands.BulkUpdate;

public class BulkUpdateApiResourceScopeCommandHandler : IRequestHandler<BulkUpdateApiResourceScopeWrapperCommand, List<BulkUpdateApiResourceScopeResponse>>
{
    private readonly IApiResourceScopeDal _apiResourceScopeDal;
    private readonly ApiResourceScopeBusinessRules _apiResourceScopeBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateApiResourceScopeCommandHandler(IMapper mapper, IApiResourceScopeDal apiResourceScopeDal, ApiResourceScopeBusinessRules apiResourceScopeBusinessRules)
    {
        _mapper = mapper;
        _apiResourceScopeDal = apiResourceScopeDal;
        _apiResourceScopeBusinessRules = apiResourceScopeBusinessRules;
    }

    public async Task<List<BulkUpdateApiResourceScopeResponse>> Handle(BulkUpdateApiResourceScopeWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _apiResourceScopeDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        _apiResourceScopeBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _apiResourceScopeDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateApiResourceScopeResponse>>(datas.Items);
    }
}



