
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.UserRefreshTokens.Commands.Update;
using IdentityServer.Application.Features.UserRefreshTokens.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.UserRefreshTokens.Handlers.Commands.Update;

public class UpdateUserRefreshTokenCommandHandler : IRequestHandler<UpdateUserRefreshTokenCommand, UpdateUserRefreshTokenResponse>
{
    private readonly IUserRefreshTokenDal _userRefreshTokenDal;
    private readonly UserRefreshTokenBusinessRules _userRefreshTokenBusinessRules;
    private readonly IMapper _mapper;

    public UpdateUserRefreshTokenCommandHandler(IMapper mapper, IUserRefreshTokenDal userRefreshTokenDal, UserRefreshTokenBusinessRules userRefreshTokenBusinessRules)
    {
        _mapper = mapper;
        _userRefreshTokenDal = userRefreshTokenDal;
        _userRefreshTokenBusinessRules = userRefreshTokenBusinessRules;
    }

    public async Task<UpdateUserRefreshTokenResponse> Handle(UpdateUserRefreshTokenCommand request, CancellationToken cancellationToken)
    {
        var data = await _userRefreshTokenDal.GetAsync(w => w.Id == request.Id);

        _userRefreshTokenBusinessRules.ThrowExceptionIfDataNull(data);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        _mapper.Map(request, data);
        await _userRefreshTokenDal.UpdateAsync(data);

        return _mapper.Map<UpdateUserRefreshTokenResponse>(data);
    }
}



