
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.Persistence.Models;
namespace IdentityServer.Domain.Entities;

public class ApiResource : Entity<Guid>
{
	public string Name { get; set; }
	public string Description { get; set; }
	public int Status { get; set; }
	public string ApiSecretSalt { get; set; }
	public string DisplayName { get; set; }
	public string ApiSecret { get; set; }
	public virtual ICollection<ApiResourceClientRelation> Clients { get; set; }
	public virtual ICollection<ApiResourceScope> ApiResourceScopes { get; set; }
}


