
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.Persistence.Models;
namespace IdentityServer.Domain.Entities;

public class Client : Entity<Guid>
{
	public byte[] ClientSecret { get; set; }
	public string Name { get; set; }
	public int Status { get; set; }
	public string ClientSecretSalt { get; set; }
	public string? ExternalId { get; set; }
	public virtual ICollection<ClientUserRelation> Users { get; set; }
	public virtual ICollection<ClientScope> ClientScopes { get; set; }
	public virtual ICollection<ApiResourceClientRelation> ApiResources { get; set; }
}


