
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.Persistence.Models;

namespace IdentityServer.Domain.Entities;

public class RoleUserRelation : Entity<Guid>
{
	public Guid RoleId { get; set; }
	public virtual Role Role { get; set; }
	public DateTime? Expiration { get; set; }
	public Guid UserId { get; set; }
	public virtual User User { get; set; }
}


