
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.Persistence.Models;
namespace IdentityServer.Domain.Entities;

public class UserPassword : Entity<Guid>
{
	public byte[] Password { get; set; }
	public byte[] PasswordSalt { get; set; }
	public Guid UserId { get; set; }
	public virtual User User { get; set; }
}


