
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using Core.Persistence.Models;
namespace Jumper.Domain.Entities;

public class EntityPropertyFeatureDefinitionProjectEntityPropertyRelation : Entity<Guid>
{
	public  Guid EntityPropertyFeatureDefinitionId { get; set; }
	public virtual EntityPropertyFeatureDefinition EntityPropertyFeatureDefinition { get; set; }
	public virtual ProjectEntityProperty ProjectEntityProperty { get; set; }
	public  Guid ProjectEntityPropertyId { get; set; }
}


