
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityFeatureDefinitions.Commands.Update;
using Jumper.Application.Features.EntityFeatureDefinitions.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using MediatR;
namespace Jumper.Application.Features.EntityFeatureDefinitions.Handlers.Commands.Update;

public class UpdateEntityFeatureDefinitionCommandHandler : IRequestHandler<UpdateEntityFeatureDefinitionCommand, UpdateEntityFeatureDefinitionResponse>
{
    private readonly IEntityFeatureDefinitionDal _entityFeatureDefinitionDal;
    private readonly EntityFeatureDefinitionBusinessRules _entityFeatureDefinitionBusinessRules;
    private readonly IMapper _mapper;

    public UpdateEntityFeatureDefinitionCommandHandler(IMapper mapper, IEntityFeatureDefinitionDal entityFeatureDefinitionDal, EntityFeatureDefinitionBusinessRules entityFeatureDefinitionBusinessRules)
    {
        _mapper = mapper;
        _entityFeatureDefinitionDal = entityFeatureDefinitionDal;
        _entityFeatureDefinitionBusinessRules = entityFeatureDefinitionBusinessRules;
    }

    public async Task<UpdateEntityFeatureDefinitionResponse> Handle(UpdateEntityFeatureDefinitionCommand request, CancellationToken cancellationToken)
    {
        var data = await _entityFeatureDefinitionDal.GetAsync(w => w.Id == request.Id);

        await _entityFeatureDefinitionBusinessRules.ThrowExceptionIfDataNull(data);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        _mapper.Map(request, data);
        await _entityFeatureDefinitionDal.UpdateAsync(data);

        return _mapper.Map<UpdateEntityFeatureDefinitionResponse>(data);
    }
}



