
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.UserPasswords.Commands.Create;

public class CreateUserPasswordCommand : IRequest<CreateUserPasswordResponse>  
{
    
	public Guid Id { get; set; }
	public byte[] Password { get; set; }
	public byte[] PasswordSalt { get; set; }
    
}




