
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using Core.ApiHelpers.JwtHelper.Models;
using Jumper.Application.Base;

namespace Jumper.Application.Features.EntityFeatureDefinitions.Rules;

public class EntityFeatureDefinitionBusinessRules : BaseBusinessRules
{

    public EntityFeatureDefinitionBusinessRules(TokenParameters tokenParameters) : base(tokenParameters)
    {
    }
}



