// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Jumper.CodeGenerator.CqrsBuilder.WebTemplates.ViewTemplates
{
    using System;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.IO;
    using System.Runtime;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using Jumper.Common.Constants;
    using Jumper.Common.DirectoryHelpers;
    using Jumper.Common.StringHelpers;
    using Jumper.Common.FileHelpers;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class LayoutTemplate : LayoutTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 20 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"

    
    string settingsJson = File.ReadAllText(FileSettings.ReadProjectPath);
    var datasource = JObject.Parse(settingsJson);
    var filePath = $"{FileSettings.ProjectCreateDirectory}{datasource["SolutionName"]}/Presentation/{datasource["SolutionName"]}.UI.Web/Views/Shared";
    DirectoryHelper.CreateDirectoryIfNotExists(filePath);

            
            #line default
            #line hidden
            this.Write("\r\n<!--\r\n   ");
            
            #line 29 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FileSettings.AUTO_GENERATED_MESSAGE));
            
            #line default
            #line hidden
            this.Write(" \r\n-->\r\n<!DOCTYPE html>\r\n<html lang=\"tr\">\r\n<head>\r\n    <meta charset=\"utf-8\" />\r\n" +
                    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n  " +
                    "  <title>@ViewData[\"Title\"] - ");
            
            #line 36 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(datasource["SolutionName"].ToString()));
            
            #line default
            #line hidden
            this.Write("</title>\r\n    <link rel=\"stylesheet\" href=\"~/css/bootstrap.min.css\" />\r\n\r\n\r\n\r\n   " +
                    " <link rel=\"shortcut icon\" href=\"~/images/ic.png\" />\r\n    <!--begin::Fonts(manda" +
                    "tory for all pages)-->\r\n    <link rel=\"stylesheet\" href=\"https://fonts.googleapi" +
                    "s.com/css?family=Inter:300,400,500,600,700\" />\r\n    <!--end::Fonts-->\r\n    <!--b" +
                    "egin::Global Stylesheets Bundle(mandatory for all pages)-->\r\n    <link href=\"~/c" +
                    "ss/plugins.bundle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"~/cs" +
                    "s/style.bundle.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <script src=\"~/js/j" +
                    "query.min.js\"></script>\r\n    <!--end::Global Stylesheets Bundle-->\r\n    <link re" +
                    "l=\"stylesheet\" href=\"~/css/site.css\" asp-append-version=\"true\" />\r\n\r\n\r\n</head>\r\n" +
                    "\r\n\r\n<!--begin::Body-->\r\n<body id=\"kt_app_body\" data-kt-app-layout=\"dark-sidebar\"" +
                    " data-kt-app-header-fixed=\"true\" data-kt-app-sidebar-enabled=\"true\" data-kt-app-" +
                    "sidebar-fixed=\"true\" data-kt-app-sidebar-hoverable=\"true\" data-kt-app-sidebar-pu" +
                    "sh-header=\"true\" data-kt-app-sidebar-push-toolbar=\"true\" data-kt-app-sidebar-pus" +
                    "h-footer=\"true\" data-kt-app-toolbar-enabled=\"true\" class=\"app-default\">\r\n    <!-" +
                    "-begin::Theme mode setup on page load-->\r\n    <!--end::Theme mode setup on page " +
                    "load-->\r\n    <!--begin::App-->\r\n    @if (TempData[\"Error\"] != null)\r\n    {\r\n    " +
                    "    <input type=\"text\" id=\"error\" hidden=\"hidden\" value=\"@TempData[\"Error\"]\" />\r" +
                    "\n    }\r\n    else if (TempData[\"Success\"] != null)\r\n    {\r\n        <input type=\"t" +
                    "ext\" id=\"success\" hidden=\"hidden\" value=\"@TempData[\"Success\"]\" />\r\n    }\r\n\r\n\r\n  " +
                    "  <div class=\"d-flex flex-column flex-root app-root\" id=\"kt_app_root\">\r\n        " +
                    "<!--begin::Page-->\r\n        <div class=\"app-page flex-column flex-column-fluid\" " +
                    "id=\"kt_app_page\">\r\n            <!--begin::Header-->\r\n            <div id=\"kt_app" +
                    "_header\" class=\"app-header\" data-kt-sticky=\"true\" data-kt-sticky-activate=\"{defa" +
                    "ult: true, lg: true}\" data-kt-sticky-name=\"app-header-minimize\" data-kt-sticky-o" +
                    "ffset=\"{default: \'200px\', lg: \'0\'}\" data-kt-sticky-animation=\"false\">\r\n         " +
                    "       <!--begin::Header container-->\r\n                <div class=\"app-container" +
                    " container-fluid d-flex align-items-stretch justify-content-between\" id=\"kt_app_" +
                    "header_container\">\r\n                    <!--begin::Sidebar mobile toggle-->\r\n   " +
                    "                 <div class=\"d-flex align-items-center d-lg-none ms-n3 me-1 me-m" +
                    "d-2\" title=\"Show sidebar menu\">\r\n                        <div class=\"btn btn-ico" +
                    "n btn-active-color-primary w-35px h-35px\" id=\"kt_app_sidebar_mobile_toggle\">\r\n  " +
                    "                          <i class=\"ki-duotone ki-abstract-14 fs-2 fs-md-1\">\r\n  " +
                    "                              <span class=\"path1\"></span>\r\n                     " +
                    "           <span class=\"path2\"></span>\r\n                            </i>\r\n      " +
                    "                  </div>\r\n                    </div>\r\n                    <!--en" +
                    "d::Sidebar mobile toggle-->\r\n                    <!--begin::Mobile logo-->\r\n    " +
                    "                <div class=\"d-flex align-items-center flex-grow-1 flex-lg-grow-0" +
                    "\">\r\n                        <a href=\"@Url.Action(\"Index\",\"Home\")\" class=\"d-lg-no" +
                    "ne\">\r\n                            <img alt=\"Logo\" src=\"~/images/logo.png\" class=" +
                    "\"h-30px\" />\r\n                        </a>\r\n                    </div>\r\n         " +
                    "           <!--end::Mobile logo-->\r\n                    <!--begin::Header wrappe" +
                    "r-->\r\n                    <div class=\"d-flex align-items-stretch justify-content" +
                    "-between flex-lg-grow-1\" id=\"kt_app_header_wrapper\">\r\n                        <!" +
                    "--begin::Menu wrapper-->\r\n                        <div class=\"app-header-menu ap" +
                    "p-header-mobile-drawer align-items-stretch\" data-kt-drawer=\"true\" data-kt-drawer" +
                    "-name=\"app-header-menu\" data-kt-drawer-activate=\"{default: true, lg: false}\" dat" +
                    "a-kt-drawer-overlay=\"true\" data-kt-drawer-width=\"250px\" data-kt-drawer-direction" +
                    "=\"end\" data-kt-drawer-toggle=\"#kt_app_header_menu_toggle\" data-kt-swapper=\"true\"" +
                    " data-kt-swapper-mode=\"{default: \'append\', lg: \'prepend\'}\" data-kt-swapper-paren" +
                    "t=\"{default: \'#kt_app_body\', lg: \'#kt_app_header_wrapper\'}\">\r\n                  " +
                    "          <div class=\"app-header-menu app-header-mobile-drawer align-items-stret" +
                    "ch\" data-kt-drawer=\"true\" data-kt-drawer-name=\"app-header-menu\" data-kt-drawer-a" +
                    "ctivate=\"{default: true, lg: false}\" data-kt-drawer-overlay=\"true\" data-kt-drawe" +
                    "r-width=\"250px\" data-kt-drawer-direction=\"end\" data-kt-drawer-toggle=\"#kt_app_he" +
                    "ader_menu_toggle\" data-kt-swapper=\"true\" data-kt-swapper-mode=\"{default: \'append" +
                    "\', lg: \'prepend\'}\" data-kt-swapper-parent=\"{default: \'#kt_app_body\', lg: \'#kt_ap" +
                    "p_header_wrapper\'}\">\r\n                                <div class=\"menu menu-roun" +
                    "ded menu-column menu-lg-row my-5 my-lg-0 align-items-stretch fw-semibold px-2 px" +
                    "-lg-0\" id=\"kt_app_header_menu\" data-kt-menu=\"true\">\r\n                           " +
                    "         <div data-kt-menu-trigger=\"{default: \'click\', lg: \'hover\'}\" data-kt-men" +
                    "u-placement=\"bottom-start\" class=\"menu-item menu-here-bg menu-lg-down-accordion " +
                    "me-0 me-lg-2\">\r\n                                        <span class=\"menu-link\">" +
                    "\r\n\r\n                                            <span class=\"menu-title\">\r\n     " +
                    "                                           ");
            
            #line 105 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(datasource["SolutionName"].ToString()));
            
            #line default
            #line hidden
            this.Write("\r\n                                            </span>\r\n\r\n                        " +
                    "                </span>\r\n                                    </div>\r\n           " +
                    "                     </div>\r\n                            </div>\r\n               " +
                    "         </div>\r\n                        <!--end::Menu wrapper-->\r\n             " +
                    "           <!--begin::Navbar-->\r\n                        <div class=\"app-navbar " +
                    "flex-shrink-0\">\r\n\r\n                            <!--begin::User menu-->\r\n        " +
                    "                    <div class=\"app-navbar-item ms-1 ms-md-4\" id=\"kt_header_user" +
                    "_menu_toggle\">\r\n                                <!--begin::Menu wrapper-->\r\n    " +
                    "                            <div class=\"cursor-pointer symbol symbol-35px\" data-" +
                    "kt-menu-trigger=\"{default: \'click\', lg: \'hover\'}\" data-kt-menu-attach=\"parent\" d" +
                    "ata-kt-menu-placement=\"bottom-end\">\r\n                                    <div cl" +
                    "ass=\"symbol\">\r\n                                        <span class=\"symbol-label" +
                    " bg-light-success\">\r\n                                            @(User.Identity" +
                    " != null ? User.Identity.Name!.ToUpper().First() : \"A\")\r\n                       " +
                    "                 </span>\r\n                                    </div>\r\n          " +
                    "                      </div>\r\n                                <!--begin::User ac" +
                    "count menu-->\r\n                                <div class=\"menu menu-sub menu-su" +
                    "b-dropdown menu-column menu-rounded menu-gray-800 menu-state-bg menu-state-color" +
                    " fw-semibold py-4 fs-6 w-275px\" data-kt-menu=\"true\">\r\n\r\n\r\n                      " +
                    "              <!--begin::Menu item-->\r\n                                    <div " +
                    "class=\"menu-item px-5\">\r\n                                        <a href=\"@Url.A" +
                    "ction(\"LogOut\",\"Auth\")\" class=\"menu-link px-5\">Çıkış Yap</a>\r\n                  " +
                    "                  </div>\r\n                                    <!--end::Menu item" +
                    "-->\r\n                                </div>\r\n                                <!-" +
                    "-end::User account menu-->\r\n                                <!--end::Menu wrappe" +
                    "r-->\r\n                            </div>\r\n                            <!--end::U" +
                    "ser menu-->\r\n                            <!--begin::Header menu toggle-->\r\n     " +
                    "                       <div class=\"app-navbar-item d-lg-none ms-2 me-n2\" title=\"" +
                    "Show header menu\">\r\n                                <div class=\"btn btn-flex btn" +
                    "-icon btn-active-color-primary w-30px h-30px\" id=\"kt_app_header_menu_toggle\">\r\n " +
                    "                                   <i class=\"ki-duotone ki-element-4 fs-1\">\r\n   " +
                    "                                     <span class=\"path1\"></span>\r\n              " +
                    "                          <span class=\"path2\"></span>\r\n                         " +
                    "           </i>\r\n                                </div>\r\n                       " +
                    "     </div>\r\n                            <!--end::Header menu toggle-->\r\n       " +
                    "                     <!--begin::Aside toggle-->\r\n                            <!-" +
                    "-end::Header menu toggle-->\r\n                        </div>\r\n                   " +
                    "     <!--end::Navbar-->\r\n\r\n\r\n\r\n                    </div>\r\n                    <" +
                    "!--end::wrapper-->\r\n\r\n\r\n                </div>\r\n                <!--end::Header " +
                    "container-->\r\n            </div>\r\n            <!--end::Header-->\r\n            <!" +
                    "--begin::Wrapper-->\r\n            <div class=\"app-wrapper flex-column flex-row-fl" +
                    "uid\" id=\"kt_app_wrapper\">\r\n\r\n                <!--begin::Sidebar-->\r\n            " +
                    "    <div id=\"kt_app_sidebar\" class=\"app-sidebar flex-column\" data-kt-drawer=\"tru" +
                    "e\" data-kt-drawer-name=\"app-sidebar\" data-kt-drawer-activate=\"{default: true, lg" +
                    ": false}\" data-kt-drawer-overlay=\"true\" data-kt-drawer-width=\"225px\" data-kt-dra" +
                    "wer-direction=\"start\" data-kt-drawer-toggle=\"#kt_app_sidebar_mobile_toggle\">\r\n  " +
                    "                  <!--begin::Logo-->\r\n                    <div class=\"app-sideba" +
                    "r-logo px-6\" id=\"kt_app_sidebar_logo\">\r\n                        <!--begin::Logo " +
                    "image-->\r\n                        <a href=\"~/home/\">\r\n                          " +
                    "  <h2>");
            
            #line 175 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(datasource["SolutionName"].ToString()));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n                            @* <img alt=\"Logo\" style=\"background-color:whi" +
                    "te\" src=\"~/assets/media/logos/logo.png\" class=\"h-25px app-sidebar-logo-default\" " +
                    "/>\r\n                            <img alt=\"Logo\" style=\"background-color:white\" s" +
                    "rc=\"~/assets/media/logos/logo.png\" class=\"h-20px app-sidebar-logo-minimize\" /> *" +
                    "@\r\n                        </a>\r\n                        <!--end::Logo image-->\r" +
                    "\n                        <!--begin::Sidebar toggle-->\r\n                        <" +
                    "!--begin::Minimized sidebar setup:\r\n                            if (isset($_COOK" +
                    "IE[\"sidebar_minimize_state\"]) && $_COOKIE[\"sidebar_minimize_state\"] === \"on\") {\r" +
                    "\n                                1. \"src/js/layout/sidebar.js\" adds \"sidebar_min" +
                    "imize_state\" cookie value to save the sidebar minimize state.\r\n                 " +
                    "               2. Set data-kt-app-sidebar-minimize=\"on\" attribute for body tag.\r" +
                    "\n                                3. Set data-kt-toggle-state=\"active\" attribute " +
                    "to the toggle element with \"kt_app_sidebar_toggle\" id.\r\n                        " +
                    "        4. Add \"active\" class to to sidebar toggle element with \"kt_app_sidebar_" +
                    "toggle\" id.\r\n                            }\r\n                        -->\r\n       " +
                    "                 <div id=\"kt_app_sidebar_toggle\" class=\"app-sidebar-toggle btn b" +
                    "tn-icon btn-shadow btn-sm btn-color-muted btn-active-color-primary h-30px w-30px" +
                    " position-absolute top-50 start-100 translate-middle rotate\" data-kt-toggle=\"tru" +
                    "e\" data-kt-toggle-state=\"active\" data-kt-toggle-target=\"body\" data-kt-toggle-nam" +
                    "e=\"app-sidebar-minimize\">\r\n                            <i class=\"ki-duotone ki-b" +
                    "lack-left-line fs-3 rotate-180\">\r\n                                <span class=\"p" +
                    "ath1\"></span>\r\n                                <span class=\"path2\"></span>\r\n    " +
                    "                        </i>\r\n                        </div>\r\n                  " +
                    "      <!--end::Sidebar toggle-->\r\n                    </div>\r\n                  " +
                    "  <!--end::Logo-->\r\n                    <!--begin::sidebar menu-->\r\n            " +
                    "        <div class=\"app-sidebar-menu overflow-hidden flex-column-fluid\">\r\n\r\n    " +
                    "                    <!--begin::Menu-->\r\n                        <div class=\"menu" +
                    " menu-rounded menu-column menu-active-bg-primary menu-hover-bg-primary menu-titl" +
                    "e-gray-700 fs-5 fw-semibold w-250px\" id=\"#kt_aside_menu\" data-kt-menu=\"true\">\r\n\r" +
                    "\n                            <div class=\"menu-item\">\r\n                          " +
                    "      <div class=\"menu-content\">\r\n                                    <span clas" +
                    "s=\"menu-heading fw-bold text-uppercase fs-7\">Menu</span>\r\n                      " +
                    "          </div>\r\n                            </div>\r\n\r\n                        " +
                    "    ");
            
            #line 210 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"

                            foreach (var entity in datasource["Entities"])
                            {
                            
            
            #line default
            #line hidden
            this.Write("\r\n                            <div class=\"menu-item\">\r\n                          " +
                    "      <a href=\"@Url.Action(\"Index\",\"");
            
            #line 216 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity["Name"].ToString()));
            
            #line default
            #line hidden
            this.Write("\")\" class=\"menu-link border-3 border-start border-transparent\">\r\n                " +
                    "                    <span class=\"menu-title\">");
            
            #line 217 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity["Name"].ToString()));
            
            #line default
            #line hidden
            this.Write(" Listesi</span>\r\n                                </a>\r\n                          " +
                    "  </div>\r\n\r\n                            ");
            
            #line 221 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"

                            }
                            
            
            #line default
            #line hidden
            this.Write("\r\n                        </div>\r\n                        <!--end::Menu-->\r\n\r\n   " +
                    "                 </div>\r\n                    <!--end::sidebar menu-->\r\n\r\n       " +
                    "         </div>\r\n                <!--end::Sidebar-->\r\n                <!--begin:" +
                    ":Main-->\r\n\r\n\r\n                <div class=\"app-main flex-column flex-row-fluid\" i" +
                    "d=\"kt_app_main\">\r\n                    <div class=\"d-flex flex-column flex-column" +
                    "-fluid mt-10\">\r\n                        <div id=\"kt_app_content\" class=\"app-cont" +
                    "ent flex-column-fluid\">\r\n                            <div id=\"kt_app_content_con" +
                    "tainer\" class=\"app-container container-xxxl\">\r\n                                @" +
                    "RenderBody()\r\n\r\n                            </div>\r\n                        </di" +
                    "v>\r\n                    </div>\r\n                </div>\r\n                <!--begi" +
                    "n::Footer-->\r\n                <div id=\"kt_app_footer\" class=\"app-footer\">\r\n     " +
                    "               <!--begin::Footer container-->\r\n                    <div class=\"a" +
                    "pp-container container-fluid d-flex flex-column flex-md-row flex-center flex-md-" +
                    "stack py-3\">\r\n                        <!--begin::Copyright-->\r\n                 " +
                    "       <div class=\"text-dark order-2 order-md-1\">\r\n                            <" +
                    "span class=\"text-muted fw-semibold me-1\">@DateTime.Now.Year &copy;</span>\r\n     " +
                    "                   </div>\r\n                        <!--end::Copyright-->\r\n      " +
                    "              </div>\r\n                    <!--end::Footer container-->\r\n        " +
                    "        </div>\r\n                <!--end::Footer-->\r\n\r\n\r\n            </div>\r\n    " +
                    "        <!--end:::Main-->\r\n\r\n        </div>\r\n        <!--end::Wrapper-->\r\n    </" +
                    "div>\r\n    <!--end::Page-->\r\n    <!--end::App-->\r\n    <!--begin::Javascript-->\r\n " +
                    "   <!--begin::Global Javascript Bundle(mandatory for all pages)-->\r\n    <script " +
                    "src=\"~/js/plugins.bundle.js\"></script>\r\n    <script src=\"~/js/scripts.bundle.js\"" +
                    "></script>\r\n    <!--end::Global Javascript Bundle-->\r\n    <!--begin::Vendors Jav" +
                    "ascript(used for this page only)-->\r\n    <!--end::Vendors Javascript-->\r\n    <!-" +
                    "-begin::Custom Javascript(used for this page only)-->\r\n    <!--end::Custom Javas" +
                    "cript-->\r\n    <!--end::Javascript-->\r\n\r\n    <script src=\"~/js/toastr.js\" asp-app" +
                    "end-version=\"true\"></script>\r\n    <script src=\"~/js/message-events.js\" asp-appen" +
                    "d-version=\"true\"></script>\r\n    <script src=\"~/js/ajax-events.js\" asp-append-ver" +
                    "sion=\"true\"></script>\r\n    <script src=\"~/js/grid-events.js\" asp-append-version=" +
                    "\"true\"></script>\r\n    <script src=\"~/js/global-events.js\" asp-append-version=\"tr" +
                    "ue\"></script>\r\n    <script src=\"~/js/sweet-alert.js\" asp-append-version=\"true\"><" +
                    "/script>\r\n    <script src=\"~/js/site.js\" asp-append-version=\"true\"></script>\r\n  " +
                    "  <script src=\"~/js/select2.js\"></script>\r\n\r\n    @await RenderSectionAsync(\"Scri" +
                    "pts\", required: false)\r\n\r\n\r\n\r\n\r\n\r\n\r\n</body>\r\n\r\n\r\n</html>\r\n\r\n");
            
            #line 301 "C:\Users\Admin\source\repos\Jumper_Freamwork\Templates\Jumper.CodeGenerator.CqrsBuilder\WebTemplates\ViewTemplates\LayoutTemplate.tt"
    
FileHelper.CreateAndClearBuilder($"{filePath}/_Layout.cshtml",this.GenerationEnvironment);


            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class LayoutTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
