
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.UserPasswords.Commands.BulkCreate;
using IdentityServer.Application.Features.UserPasswords.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;

using MediatR;
namespace IdentityServer.Application.Features.UserPasswords.Handlers.Commands.BulkCreate;

public class BulkCreateUserPasswordCommandHandler : IRequestHandler<BulkCreateUserPasswordWrapperCommand, List<BulkCreateUserPasswordResponse>>
{
    private readonly IUserPasswordDal _userPasswordDal;
    private readonly UserPasswordBusinessRules _userPasswordBusinessRules;
    private readonly IMapper _mapper;

    public BulkCreateUserPasswordCommandHandler(IMapper mapper, IUserPasswordDal userPasswordDal, UserPasswordBusinessRules userPasswordBusinessRules)
    {
        _mapper = mapper;
        _userPasswordDal = userPasswordDal;
        _userPasswordBusinessRules = userPasswordBusinessRules;
    }

    public async Task<List<BulkCreateUserPasswordResponse>> Handle(BulkCreateUserPasswordWrapperCommand request, CancellationToken cancellationToken)
    {
        var datas = _mapper.Map<List<UserPassword>>(request);

        _userPasswordBusinessRules.SetId(datas);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _userPasswordDal.AddRangeAsync(datas);

        return _mapper.Map<List<BulkCreateUserPasswordResponse>>(datas);
    }
}



