
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 24.10.2023 10:52
//---------------------------------------------------------------------------------------

using IdentityServer.Application.Features.ClientUserRelations.Commands.Create;
using IdentityServer.Application.Features.ClientUserRelations.Commands.DeleteById;
using IdentityServer.Application.Features.ClientUserRelations.Commands.Update;
using IdentityServer.Application.Features.ClientUserRelations.Queries.GetById;
using IdentityServer.Application.Features.ClientUserRelations.Queries.ListDynamic;
using IdentityServer.UI.Api.ActionFilters;
using IdentityServer.UI.Api.Controllers.Base;
using Core.Persistence.Models.Responses;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Specialized;
using System.Web;
using Core.WebHelper.NameValueCollectionHelpers;
using IdentityServer.Domain.Entities;

namespace IdentityServer.UI.Api.Controllers
{
    [Route("ClientUserRelations")]
    public class ClientUserRelationsController : MediatrController
    {
        [HttpGet("{id}")]
        public async Task<IActionResult> GetByIdAsync(Guid id)
        {
            var response = await base.Mediator.Send(new GetByIdClientUserRelationQuery { Id = id });
            return Ok(Response<GetByIdClientUserRelationResponse>.Success(response,200));
        }

        [HttpGet("getlist")]
        public async Task<IActionResult> ListAsync(NameValueCollection collection)
        {
            var query = new ListDynamicClientUserRelationQuery
            {
                DynamicQuery = collection.ToDynamicFilter<ClientUserRelation>(),
                PageRequest = collection.ToPageRequest()
            };
            var response = await base.Mediator.Send(query);

            return Ok(Response<ListModel<ListDynamicClientUserRelationResponse>>.Success(response,200));
        }

        [HttpPost("list")]
        public async Task<IActionResult> ListAsync(ListDynamicClientUserRelationQuery query)
        {
            var response = await base.Mediator.Send(query);
            return Ok(Response<ListModel<ListDynamicClientUserRelationResponse>>.Success(response,200));
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(CreateClientUserRelationCommand request)
        {
            return Ok(Response<CreateClientUserRelationResponse>.Success(await base.Mediator.Send(request), 200));
        }

        [HttpPut]
        public async Task<IActionResult> UpdateAsync(UpdateClientUserRelationCommand request)
        {
            return Ok(Response<UpdateClientUserRelationResponse>.Success(await base.Mediator.Send(request), 200));
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteByIdAsync(Guid id)
        {
            return Ok(Response<DeleteByIdClientUserRelationResponse>.Success(await base.Mediator.Send(new DeleteByIdClientUserRelationCommand { Id = id }), 200));
        }

    }
}


