
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using IdentityServer.Application.Features.Users.Commands.Create;
using IdentityServer.Application.Features.Users.Commands.DeleteById;
using IdentityServer.Application.Features.Users.Commands.Update;
using IdentityServer.Application.Features.Users.Queries.GetById;
using IdentityServer.Application.Features.Users.Queries.ListDynamic;
using IdentityServer.UI.Api.ActionFilters;
using IdentityServer.UI.Api.Controllers.Base;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Specialized;
using System.Web;
using Core.WebHelper.NameValueCollectionHelpers;
using IdentityServer.Domain.Entities;
using Core.Persistence.Models.Responses;

namespace IdentityServer.UI.Api.Controllers
{
    [Route("Users")]
    public class UsersController : MediatrController
    {
        [HttpGet("{id}")]
        public async Task<IActionResult> GetByIdAsync(Guid id)
        {
            var response = await base.Mediator.Send(new GetByIdUserQuery { Id = id });
            return Ok(Response<GetByIdUserResponse>.Success(response,200));
        }

        [HttpGet("getlist")]
        public async Task<IActionResult> ListAsync(NameValueCollection collection)
        {
            var query = new ListDynamicUserQuery
            {
                DynamicQuery = collection.ToDynamicFilter<User>(),
                PageRequest = collection.ToPageRequest()
            };
            var response = await base.Mediator.Send(query);

            return Ok(Response<ListModel<ListDynamicUserResponse>>.Success(response, 200));
        }

        [HttpPost("list")]
        public async Task<IActionResult> ListAsync(ListDynamicUserQuery query)
        {
            var response = await base.Mediator.Send(query);
            return Ok(response);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(CreateUserCommand request)
        {
            return Ok(await base.Mediator.Send(request));
        }

        [HttpPut]
        public async Task<IActionResult> UpdateAsync(UpdateUserCommand request)
        {
            return Ok(await base.Mediator.Send(request));
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteByIdAsync(Guid id)
        {
            return Ok(await base.Mediator.Send(new DeleteByIdUserCommand { Id = id }));
        }

    }
}


