
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 24.10.2023 10:52
//---------------------------------------------------------------------------------------

using IdentityServer.Application.Features.UserRefreshTokens.Commands.Create;
using IdentityServer.Application.Features.UserRefreshTokens.Commands.DeleteById;
using IdentityServer.Application.Features.UserRefreshTokens.Commands.Update;
using IdentityServer.Application.Features.UserRefreshTokens.Queries.GetById;
using IdentityServer.Application.Features.UserRefreshTokens.Queries.ListDynamic;
using IdentityServer.UI.Api.ActionFilters;
using IdentityServer.UI.Api.Controllers.Base;
using Core.Persistence.Models.Responses;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Specialized;
using System.Web;
using Core.WebHelper.NameValueCollectionHelpers;
using IdentityServer.Domain.Entities;

namespace IdentityServer.UI.Api.Controllers
{
    [Route("UserRefreshTokens")]
    public class UserRefreshTokensController : MediatrController
    {
        [HttpGet("{id}")]
        public async Task<IActionResult> GetByIdAsync(Guid id)
        {
            var response = await base.Mediator.Send(new GetByIdUserRefreshTokenQuery { Id = id });
            return Ok(Response<GetByIdUserRefreshTokenResponse>.Success(response,200));
        }

        [HttpGet("getlist")]
        public async Task<IActionResult> ListAsync(NameValueCollection collection)
        {
            var query = new ListDynamicUserRefreshTokenQuery
            {
                DynamicQuery = collection.ToDynamicFilter<UserRefreshToken>(),
                PageRequest = collection.ToPageRequest()
            };
            var response = await base.Mediator.Send(query);

            return Ok(Response<ListModel<ListDynamicUserRefreshTokenResponse>>.Success(response,200));
        }

        [HttpPost("list")]
        public async Task<IActionResult> ListAsync(ListDynamicUserRefreshTokenQuery query)
        {
            var response = await base.Mediator.Send(query);
            return Ok(Response<ListModel<ListDynamicUserRefreshTokenResponse>>.Success(response,200));
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(CreateUserRefreshTokenCommand request)
        {
            return Ok(Response<CreateUserRefreshTokenResponse>.Success(await base.Mediator.Send(request), 200));
        }

        [HttpPut]
        public async Task<IActionResult> UpdateAsync(UpdateUserRefreshTokenCommand request)
        {
            return Ok(Response<UpdateUserRefreshTokenResponse>.Success(await base.Mediator.Send(request), 200));
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteByIdAsync(Guid id)
        {
            return Ok(Response<DeleteByIdUserRefreshTokenResponse>.Success(await base.Mediator.Send(new DeleteByIdUserRefreshTokenCommand { Id = id }), 200));
        }

    }
}


