


//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using MediatR;
using Core.Application.Pipelines.Caching;
using Core.Application.Pipelines.Logging;
using Jumper.Application.Base;
using Core.Persistence.Models.Responses;
namespace Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Queries.ListDynamic;

public class ListDynamicEntityFeatureDefinitionProjectEntityRelationQuery : BaseDynamicQuery, IRequest<ListModel<ListDynamicEntityFeatureDefinitionProjectEntityRelationResponse>>  
{
    
    
}




