



//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.BulkUpdate;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using MediatR;
namespace Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Handlers.Commands.BulkUpdate;

public class BulkUpdateEntityFeatureDefinitionProjectEntityRelationCommandHandler : IRequestHandler<BulkUpdateEntityFeatureDefinitionProjectEntityRelationWrapperCommand, List<BulkUpdateEntityFeatureDefinitionProjectEntityRelationResponse>>
{
    private readonly IEntityFeatureDefinitionProjectEntityRelationDal _entityFeatureDefinitionProjectEntityRelationDal;
    private readonly EntityFeatureDefinitionProjectEntityRelationBusinessRules _entityFeatureDefinitionProjectEntityRelationBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateEntityFeatureDefinitionProjectEntityRelationCommandHandler(IMapper mapper, IEntityFeatureDefinitionProjectEntityRelationDal entityFeatureDefinitionProjectEntityRelationDal, EntityFeatureDefinitionProjectEntityRelationBusinessRules entityFeatureDefinitionProjectEntityRelationBusinessRules)
    {
        _mapper = mapper;
        _entityFeatureDefinitionProjectEntityRelationDal = entityFeatureDefinitionProjectEntityRelationDal;
        _entityFeatureDefinitionProjectEntityRelationBusinessRules = entityFeatureDefinitionProjectEntityRelationBusinessRules;
    }

    public async Task<List<BulkUpdateEntityFeatureDefinitionProjectEntityRelationResponse>> Handle(BulkUpdateEntityFeatureDefinitionProjectEntityRelationWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _entityFeatureDefinitionProjectEntityRelationDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        _entityFeatureDefinitionProjectEntityRelationBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _entityFeatureDefinitionProjectEntityRelationDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateEntityFeatureDefinitionProjectEntityRelationResponse>>(datas.Items);
    }
}



