
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.RoleScopes.Commands.Create;

public class CreateRoleScopeCommandValidator : AbstractValidator<CreateRoleScopeCommand>
{
    public CreateRoleScopeCommandValidator()
    {
         
		RuleFor(w => w.Scope).NotEmpty().NotNull().WithMessage("Lütfen Scope Alanını Doldurun veya Seçin.");

        
    }
}





