
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

namespace IdentityServer.Application.Features.Roles.Commands.Create;

public class CreateRoleResponse
{
    
	public DateTime DeletedTime { get; set; }
	public string Name { get; set; }
	public DateTime UpdatedTime { get; set; }
	public Guid Id { get; set; }
	public DateTime CreatedTime { get; set; }
    
}




