
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.Clients.Commands.BulkUpdate;
using IdentityServer.Application.Features.Clients.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.Clients.Handlers.Commands.BulkUpdate;

public class BulkUpdateClientCommandHandler : IRequestHandler<BulkUpdateClientWrapperCommand, List<BulkUpdateClientResponse>>
{
    private readonly IClientDal _clientDal;
    private readonly ClientBusinessRules _clientBusinessRules;
    private readonly IMapper _mapper;

    public BulkUpdateClientCommandHandler(IMapper mapper, IClientDal clientDal, ClientBusinessRules clientBusinessRules)
    {
        _mapper = mapper;
        _clientDal = clientDal;
        _clientBusinessRules = clientBusinessRules;
    }

    public async Task<List<BulkUpdateClientResponse>> Handle(BulkUpdateClientWrapperCommand request, CancellationToken cancellationToken)
    {
        var ids = request.Items.Select(q => q.Id).ToList();
        var datas = await _clientDal.GetListAsync(w => ids.Contains(w.Id), cancellationToken : cancellationToken);

        _clientBusinessRules.ThrowExceptionIfDataNull(datas);
        
        //İş Kurallarınızı Burada Çağırabilirsiniz.
        foreach(var item in datas.Items)
        {
             var selectedRequest = request.Items.FirstOrDefault(w => w.Id == item.Id);
             if (selectedRequest == null)
             {
                continue;
             }
            _mapper.Map(selectedRequest, item);
        }
        
        await _clientDal.UpdateRangeAsync(datas.Items);

        return _mapper.Map<List<BulkUpdateClientResponse>>(datas.Items);
    }
}



