
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.AuthMessageses.Commands.DeleteById;

public class DeleteByIdAuthMessagesCommandValidator : AbstractValidator<DeleteByIdAuthMessagesCommand>
{
    public DeleteByIdAuthMessagesCommandValidator()
    {
         

        
    }
}





