
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.RoleUserRelations.Commands.Update;

public class UpdateRoleUserRelationCommand : IRequest<UpdateRoleUserRelationResponse>  
{
    
	public Guid Id { get; set; }
	public Guid RoleId { get; set; }
	public DateTime? Expiration { get; set; }
	public Guid UserId { get; set; }
    
}




