
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;
using IdentityServer.Application.Base;
using Core.Persistence.Models.Responses;
namespace IdentityServer.Application.Features.Users.Queries.ListDynamic;

public class ListDynamicUserQuery : BaseDynamicQuery, IRequest<ListModel<ListDynamicUserResponse>>  
{
    
    
}




