
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.RoleUserRelations.Commands.BulkCreate;

public class BulkCreateRoleUserRelationCommandValidator : AbstractValidator<BulkCreateRoleUserRelationCommand>
{
    public BulkCreateRoleUserRelationCommandValidator()
    {
         
		RuleFor(w => w.RoleId).NotEmpty().NotNull().WithMessage("Lütfen RoleId Alanını Doldurun veya Seçin.");
		RuleFor(w => w.UserId).NotEmpty().NotNull().WithMessage("Lütfen UserId Alanını Doldurun veya Seçin.");

        
    }
}





