
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.ClientScopes.Commands.Create;
using IdentityServer.Application.Features.ClientScopes.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.ClientScopes.Handlers.Commands.Create;

public class CreateClientScopeCommandHandler : IRequestHandler<CreateClientScopeCommand, CreateClientScopeResponse>
{
    private readonly IClientScopeDal _clientScopeDal;
    private readonly ClientScopeBusinessRules _clientScopeBusinessRules;
    private readonly IMapper _mapper;

    public CreateClientScopeCommandHandler(IMapper mapper, IClientScopeDal clientScopeDal, ClientScopeBusinessRules clientScopeBusinessRules)
    {
        _mapper = mapper;
        _clientScopeDal = clientScopeDal;
        _clientScopeBusinessRules = clientScopeBusinessRules;
    }

    public async Task<CreateClientScopeResponse> Handle(CreateClientScopeCommand request, CancellationToken cancellationToken)
    {
        var data = _mapper.Map<ClientScope>(request);

        _clientScopeBusinessRules.SetId(data);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _clientScopeDal.AddAsync(data);

        return _mapper.Map<CreateClientScopeResponse>(data);
    }
}



