
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.Roles.Commands.BulkUpdate;


public class BulkUpdateRoleWrapperCommand : IRequest<List<BulkUpdateRoleResponse>>  
{
    public List<BulkUpdateRoleCommand> Items { get; set; }
}

public class BulkUpdateRoleCommand
{
    
	public string Name { get; set; }
	public Guid Id { get; set; }
    
}




