
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.Users.Commands.BulkCreate;
using IdentityServer.Application.Features.Users.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;

using MediatR;
namespace IdentityServer.Application.Features.Users.Handlers.Commands.BulkCreate;

public class BulkCreateUserCommandHandler : IRequestHandler<BulkCreateUserWrapperCommand, List<BulkCreateUserResponse>>
{
    private readonly IUserDal _userDal;
    private readonly UserBusinessRules _userBusinessRules;
    private readonly IMapper _mapper;

    public BulkCreateUserCommandHandler(IMapper mapper, IUserDal userDal, UserBusinessRules userBusinessRules)
    {
        _mapper = mapper;
        _userDal = userDal;
        _userBusinessRules = userBusinessRules;
    }

    public async Task<List<BulkCreateUserResponse>> Handle(BulkCreateUserWrapperCommand request, CancellationToken cancellationToken)
    {
        var datas = _mapper.Map<List<User>>(request);

        _userBusinessRules.SetId(datas);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _userDal.AddRangeAsync(datas);

        return _mapper.Map<List<BulkCreateUserResponse>>(datas);
    }
}



