
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using Core.Persistence.Models.Responses;
using Core.Persistence.Paging;
using IdentityServer.Application.Features.ClientUserRelations.Commands.BulkCreate;
using IdentityServer.Application.Features.ClientUserRelations.Commands.Create;
using IdentityServer.Application.Features.ClientUserRelations.Commands.Update;
using IdentityServer.Application.Features.ClientUserRelations.Commands.BulkUpdate;
using IdentityServer.Application.Features.ClientUserRelations.Commands.DeleteById;
using IdentityServer.Application.Features.ClientUserRelations.Queries.ListDynamic;
using IdentityServer.Application.Features.ClientUserRelations.Queries.GetById;
using IdentityServer.Domain.Entities;

namespace IdentityServer.Application.Features.ClientUserRelations.Profiles;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        
		CreateMap<BulkCreateClientUserRelationCommand,ClientUserRelation>();
		CreateMap<ClientUserRelation, BulkCreateClientUserRelationResponse>();
		CreateMap<CreateClientUserRelationCommand,ClientUserRelation>();
		CreateMap<ClientUserRelation, CreateClientUserRelationResponse>();
		CreateMap<UpdateClientUserRelationCommand,ClientUserRelation>();
		CreateMap<ClientUserRelation, UpdateClientUserRelationResponse>();
		CreateMap<BulkUpdateClientUserRelationCommand,ClientUserRelation>();
		CreateMap<ClientUserRelation, BulkUpdateClientUserRelationResponse>();
		CreateMap<DeleteByIdClientUserRelationCommand,ClientUserRelation>();
		CreateMap<ClientUserRelation, DeleteByIdClientUserRelationResponse>();
		CreateMap<Paginate<ClientUserRelation>, ListModel<ListDynamicClientUserRelationResponse>>();
		CreateMap<ClientUserRelation, ListDynamicClientUserRelationResponse>();
		CreateMap<ClientUserRelation, GetByIdClientUserRelationResponse>();
    }
}




