
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.UserPasswords.Queries.GetById;
using IdentityServer.Application.Features.UserPasswords.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.UserPasswords.Handlers.Queries.GetById;

public class GetByIdUserPasswordQueryHandler : IRequestHandler<GetByIdUserPasswordQuery, GetByIdUserPasswordResponse>
{
    private readonly IUserPasswordDal _userPasswordDal;
    private readonly UserPasswordBusinessRules _userPasswordBusinessRules;
    private readonly IMapper _mapper;

    public GetByIdUserPasswordQueryHandler(IMapper mapper, IUserPasswordDal userPasswordDal, UserPasswordBusinessRules userPasswordBusinessRules)
    {
        _mapper = mapper;
        _userPasswordDal = userPasswordDal;
        _userPasswordBusinessRules = userPasswordBusinessRules;
    }

    public async Task<GetByIdUserPasswordResponse> Handle(GetByIdUserPasswordQuery request, CancellationToken cancellationToken)
    {
        
        var data = await _userPasswordDal.GetAsync(w => w.Id == request.Id, cancellationToken : cancellationToken);
            
        _userPasswordBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        return _mapper.Map<GetByIdUserPasswordResponse>(data);
    }
}



