
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.ApiHelpers.JwtHelper.Models;
using IdentityServer.Application.Base;

namespace IdentityServer.Application.Features.RoleScopes.Rules;

public class RoleScopeBusinessRules : BaseBusinessRules
{

    public RoleScopeBusinessRules(TokenParameters tokenParameters) : base(tokenParameters)
    {
    }
}



