
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using Core.Persistence.Models.Responses;
using Core.Persistence.Paging;
using IdentityServer.Application.Features.RoleScopes.Commands.BulkCreate;
using IdentityServer.Application.Features.RoleScopes.Commands.Create;
using IdentityServer.Application.Features.RoleScopes.Commands.Update;
using IdentityServer.Application.Features.RoleScopes.Commands.BulkUpdate;
using IdentityServer.Application.Features.RoleScopes.Commands.DeleteById;
using IdentityServer.Application.Features.RoleScopes.Queries.ListDynamic;
using IdentityServer.Application.Features.RoleScopes.Queries.GetById;
using IdentityServer.Domain.Entities;

namespace IdentityServer.Application.Features.RoleScopes.Profiles;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        
		CreateMap<BulkCreateRoleScopeCommand,RoleScope>();
		CreateMap<RoleScope, BulkCreateRoleScopeResponse>();
		CreateMap<CreateRoleScopeCommand,RoleScope>();
		CreateMap<RoleScope, CreateRoleScopeResponse>();
		CreateMap<UpdateRoleScopeCommand,RoleScope>();
		CreateMap<RoleScope, UpdateRoleScopeResponse>();
		CreateMap<BulkUpdateRoleScopeCommand,RoleScope>();
		CreateMap<RoleScope, BulkUpdateRoleScopeResponse>();
		CreateMap<DeleteByIdRoleScopeCommand,RoleScope>();
		CreateMap<RoleScope, DeleteByIdRoleScopeResponse>();
		CreateMap<Paginate<RoleScope>, ListModel<ListDynamicRoleScopeResponse>>();
		CreateMap<RoleScope, ListDynamicRoleScopeResponse>();
		CreateMap<RoleScope, GetByIdRoleScopeResponse>();
    }
}




