
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.Users.Commands.DeleteById;

public class DeleteByIdUserCommandValidator : AbstractValidator<DeleteByIdUserCommand>
{
    public DeleteByIdUserCommandValidator()
    {
         

        
    }
}





