
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.Clients.Commands.Update;

public class UpdateClientCommand : IRequest<UpdateClientResponse>  
{
    
	public byte[] ClientSecret { get; set; }
	public string Name { get; set; }
	public int Status { get; set; }
	public Guid Id { get; set; }
	public string ClientSecretSalt { get; set; }
	public string? ExternalId { get; set; } = null!;
    
}




