
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.Roles.Commands.BulkCreate;


public class BulkCreateRoleWrapperCommand : IRequest<List<BulkCreateRoleResponse>>  
{
    public List<BulkCreateRoleCommand> Items { get; set; }
}

public class BulkCreateRoleCommand
{
    
	public string Name { get; set; }
	public Guid Id { get; set; }
    
}




