
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.ClientUserRelations.Commands.DeleteById;

public class DeleteByIdClientUserRelationCommandValidator : AbstractValidator<DeleteByIdClientUserRelationCommand>
{
    public DeleteByIdClientUserRelationCommandValidator()
    {
         

        
    }
}





