
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Commands.DeleteById;
using Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using MediatR;
namespace Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Handlers.Commands.DeleteById;

public class DeleteByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationCommandHandler : IRequestHandler<DeleteByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationCommand, DeleteByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse>
{
    private readonly IEntityPropertyFeatureDefinitionProjectEntityPropertyRelationDal _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal;
    private readonly EntityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules;
    private readonly IMapper _mapper;

    public DeleteByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationCommandHandler(IMapper mapper, IEntityPropertyFeatureDefinitionProjectEntityPropertyRelationDal entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal, EntityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules)
    {
        _mapper = mapper;
        _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal = entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal;
        _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules = entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules;
    }

    public async Task<DeleteByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse> Handle(DeleteByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationCommand request, CancellationToken cancellationToken)
    {
        
        var data = await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal.GetAsync(w => w.Id == request.Id);
            
        await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal.DeleteAsync(data!);

        return _mapper.Map<DeleteByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse>(data);
    }
}



