
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.RoleUserRelations.Commands.BulkCreate;
using IdentityServer.Application.Features.RoleUserRelations.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;

using MediatR;
namespace IdentityServer.Application.Features.RoleUserRelations.Handlers.Commands.BulkCreate;

public class BulkCreateRoleUserRelationCommandHandler : IRequestHandler<BulkCreateRoleUserRelationWrapperCommand, List<BulkCreateRoleUserRelationResponse>>
{
    private readonly IRoleUserRelationDal _roleUserRelationDal;
    private readonly RoleUserRelationBusinessRules _roleUserRelationBusinessRules;
    private readonly IMapper _mapper;

    public BulkCreateRoleUserRelationCommandHandler(IMapper mapper, IRoleUserRelationDal roleUserRelationDal, RoleUserRelationBusinessRules roleUserRelationBusinessRules)
    {
        _mapper = mapper;
        _roleUserRelationDal = roleUserRelationDal;
        _roleUserRelationBusinessRules = roleUserRelationBusinessRules;
    }

    public async Task<List<BulkCreateRoleUserRelationResponse>> Handle(BulkCreateRoleUserRelationWrapperCommand request, CancellationToken cancellationToken)
    {
        var datas = _mapper.Map<List<RoleUserRelation>>(request);

        _roleUserRelationBusinessRules.SetId(datas);
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _roleUserRelationDal.AddRangeAsync(datas);

        return _mapper.Map<List<BulkCreateRoleUserRelationResponse>>(datas);
    }
}



