
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Queries.GetById;
using Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using MediatR;
namespace Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Handlers.Queries.GetById;

public class GetByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationQueryHandler : IRequestHandler<GetByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationQuery, GetByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse>
{
    private readonly IEntityPropertyFeatureDefinitionProjectEntityPropertyRelationDal _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal;
    private readonly EntityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules;
    private readonly IMapper _mapper;

    public GetByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationQueryHandler(IMapper mapper, IEntityPropertyFeatureDefinitionProjectEntityPropertyRelationDal entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal, EntityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules)
    {
        _mapper = mapper;
        _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal = entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal;
        _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules = entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules;
    }

    public async Task<GetByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse> Handle(GetByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationQuery request, CancellationToken cancellationToken)
    {
        
        var data = await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationDal.GetAsync(w => w.Id == request.Id, cancellationToken : cancellationToken);
            
        await _entityPropertyFeatureDefinitionProjectEntityPropertyRelationBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        return _mapper.Map<GetByIdEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse>(data);
    }
}



