
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityFeatureDefinitions.Queries.ListDynamic;
using Jumper.Application.Features.EntityFeatureDefinitions.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using Core.Persistence.Models.Responses;
using MediatR;
namespace Jumper.Application.Features.EntityFeatureDefinitions.Handlers.Queries.ListDynamic;

public class ListDynamicEntityFeatureDefinitionQueryHandler : IRequestHandler<ListDynamicEntityFeatureDefinitionQuery, ListModel<ListDynamicEntityFeatureDefinitionResponse>>
{
    private readonly IEntityFeatureDefinitionDal _entityFeatureDefinitionDal;
    private readonly EntityFeatureDefinitionBusinessRules _entityFeatureDefinitionBusinessRules;
    private readonly IMapper _mapper;

    public ListDynamicEntityFeatureDefinitionQueryHandler(IMapper mapper, IEntityFeatureDefinitionDal entityFeatureDefinitionDal, EntityFeatureDefinitionBusinessRules entityFeatureDefinitionBusinessRules)
    {
        _mapper = mapper;
        _entityFeatureDefinitionDal = entityFeatureDefinitionDal;
        _entityFeatureDefinitionBusinessRules = entityFeatureDefinitionBusinessRules;
    }

    public async Task<ListModel<ListDynamicEntityFeatureDefinitionResponse>> Handle(ListDynamicEntityFeatureDefinitionQuery request, CancellationToken cancellationToken)
    {
        
        var datas = await _entityFeatureDefinitionDal.GetListByDynamicAsync(request.DynamicQuery, size: request.PageRequest.PageSize, index: request.PageRequest.PageIndex, cancellationToken : cancellationToken);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        var returnData = _mapper.Map<ListModel<ListDynamicEntityFeatureDefinitionResponse>>(datas);
        _entityFeatureDefinitionBusinessRules.FillDynamicFilter(returnData, request.DynamicQuery, request.PageRequest);
        return returnData;

    }
}



