
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using IdentityServer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace IdentityServer.Persistence.EntityConfigurations;


public class ApiResourceConfiguration : IEntityTypeConfiguration<ApiResource>
{
    public void Configure(EntityTypeBuilder<ApiResource> builder)
    {
        builder.ToTable("ApiResources").HasKey(t => t.Id);
        builder.HasQueryFilter(w => !w.DeletedTime.HasValue);

    
		builder.Property(w => w.CreatedTime).HasColumnName("CreatedTime").IsRequired();
		builder.Property(w => w.Name).HasColumnName("Name").IsRequired();
		builder.Property(w => w.Description).HasColumnName("Description").IsRequired();
		builder.Property(w => w.DeletedTime).HasColumnName("DeletedTime");
		builder.Property(w => w.Status).HasColumnName("Status").IsRequired();
		builder.Property(w => w.UpdatedTime).HasColumnName("UpdatedTime");
		builder.Property(w => w.Id).HasColumnName("Id").IsRequired();
		builder.Property(w => w.ApiSecretSalt).HasColumnName("ApiSecretSalt").IsRequired();
		builder.Property(w => w.DisplayName).HasColumnName("DisplayName").IsRequired();
		builder.Property(w => w.ApiSecret).HasColumnName("ApiSecret").IsRequired();
		builder.HasMany(w => w.ApiResourceScopes);
        
        


    }
}





