
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using IdentityServer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace IdentityServer.Persistence.EntityConfigurations;


public class ClientConfiguration : IEntityTypeConfiguration<Client>
{
    public void Configure(EntityTypeBuilder<Client> builder)
    {
        builder.ToTable("Clients").HasKey(t => t.Id);
        builder.HasQueryFilter(w => !w.DeletedTime.HasValue);

    
		builder.Property(w => w.ClientSecret).HasColumnName("ClientSecret").IsRequired();
		builder.Property(w => w.UpdatedTime).HasColumnName("UpdatedTime");
		builder.Property(w => w.CreatedTime).HasColumnName("CreatedTime").IsRequired();
		builder.Property(w => w.DeletedTime).HasColumnName("DeletedTime");
		builder.Property(w => w.Name).HasColumnName("Name").IsRequired();
		builder.Property(w => w.Status).HasColumnName("Status").IsRequired();
		builder.Property(w => w.Id).HasColumnName("Id").IsRequired();
		builder.Property(w => w.ClientSecretSalt).HasColumnName("ClientSecretSalt").IsRequired();
		builder.Property(w => w.ExternalId).HasColumnName("ExternalId");
		builder.HasMany(w => w.ClientScopes);
        
        


    }
}





