
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using IdentityServer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace IdentityServer.Persistence.EntityConfigurations;


public class RoleUserRelationConfiguration : IEntityTypeConfiguration<RoleUserRelation>
{
    public void Configure(EntityTypeBuilder<RoleUserRelation> builder)
    {
        builder.ToTable("RoleUserRelations").HasKey(t => t.Id);
        builder.HasQueryFilter(w => !w.DeletedTime.HasValue);

    
		builder.Property(w => w.CreatedTime).HasColumnName("CreatedTime").IsRequired();
		builder.Property(w => w.Id).HasColumnName("Id").IsRequired();
		builder.Property(w => w.RoleId).HasColumnName("RoleId").IsRequired();
		builder.Property(w => w.Expiration).HasColumnName("Expiration");
		builder.Property(w => w.UserId).HasColumnName("UserId").IsRequired();
		builder.Property(w => w.DeletedTime).HasColumnName("DeletedTime");
		builder.Property(w => w.UpdatedTime).HasColumnName("UpdatedTime");
        
        


    }
}





