
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using IdentityServer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace IdentityServer.Persistence.EntityConfigurations;


public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users").HasKey(t => t.Id);
        builder.HasQueryFilter(w => !w.DeletedTime.HasValue);

    
		builder.Property(w => w.LastName).HasColumnName("LastName").IsRequired();
		builder.Property(w => w.UserName).HasColumnName("UserName").IsRequired();
		builder.Property(w => w.NormalizedMailAddress).HasColumnName("NormalizedMailAddress").IsRequired();
		builder.Property(w => w.MailAddress).HasColumnName("MailAddress").IsRequired();
		builder.Property(w => w.NormalizedUserName).HasColumnName("NormalizedUserName").IsRequired();
		builder.Property(w => w.CreatedTime).HasColumnName("CreatedTime").IsRequired();
		builder.Property(w => w.DeletedTime).HasColumnName("DeletedTime");
		builder.Property(w => w.FirstName).HasColumnName("FirstName").IsRequired();
		builder.Property(w => w.UpdatedTime).HasColumnName("UpdatedTime");
		builder.Property(w => w.Id).HasColumnName("Id").IsRequired();
		builder.Property(w => w.Status).HasColumnName("Status").IsRequired();
		builder.HasMany(w => w.UserScopes);
		builder.HasMany(w => w.UserRefreshTokens);
		builder.HasMany(w => w.UserPasswords);
        
        


    }
}





