
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using FluentValidation;
namespace IdentityServer.Application.Features.ApiResourceClientRelations.Commands.Update;

public class UpdateApiResourceClientRelationCommandValidator : AbstractValidator<UpdateApiResourceClientRelationCommand>
{
    public UpdateApiResourceClientRelationCommandValidator()
    {
         
		RuleFor(w => w.ClientId).NotEmpty().NotNull().WithMessage("Lütfen ClientId Alanını Doldurun veya Seçin.");
		RuleFor(w => w.ApiResourceId).NotEmpty().NotNull().WithMessage("Lütfen ApiResourceId Alanını Doldurun veya Seçin.");

        
    }
}





