

//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.Persistence.Models;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Persistence.Contexts;
using IdentityServer.Persistence.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace IdentityServer.Persistence;

public static class PersistenceServiceRegistration
{
    public static IServiceCollection AddPersistenceServices(this IServiceCollection services,IConfiguration configuration)
    {
        #region Db Options

        DatabaseOptions opts = new DatabaseOptions();

        configuration.GetSection("DatabaseOptions").Bind(opts);
        services.Configure<DatabaseOptions>(options =>
        {
            options = opts;
        });
        services.AddSingleton(sp =>
        {
            return opts;
        });


        #endregion

        services.AddDbContext<IdentityServerDbContext>(options => options.UseSqlServer(opts.EfConnectionString));
        

		services.AddScoped<IUserScopeDal, UserScopeDal>();

		services.AddScoped<IClientScopeDal, ClientScopeDal>();

		services.AddScoped<IUserRefreshTokenDal, UserRefreshTokenDal>();

		services.AddScoped<IClientDal, ClientDal>();

		services.AddScoped<IAuthMessagesDal, AuthMessagesDal>();

		services.AddScoped<IUserDal, UserDal>();

		services.AddScoped<IRoleDal, RoleDal>();

		services.AddScoped<IApiResourceDal, ApiResourceDal>();

		services.AddScoped<IRoleScopeDal, RoleScopeDal>();

		services.AddScoped<IApiResourceClientRelationDal, ApiResourceClientRelationDal>();

		services.AddScoped<IApiResourceScopeDal, ApiResourceScopeDal>();

		services.AddScoped<IClientUserRelationDal, ClientUserRelationDal>();

		services.AddScoped<IUserPasswordDal, UserPasswordDal>();

		services.AddScoped<IRoleUserRelationDal, RoleUserRelationDal>();

        return services;
    }
}
