
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using Core.Persistence.Models.Responses;
using Core.Persistence.Paging;
using IdentityServer.Application.Features.AuthMessageses.Commands.BulkCreate;
using IdentityServer.Application.Features.AuthMessageses.Commands.Create;
using IdentityServer.Application.Features.AuthMessageses.Commands.Update;
using IdentityServer.Application.Features.AuthMessageses.Commands.BulkUpdate;
using IdentityServer.Application.Features.AuthMessageses.Commands.DeleteById;
using IdentityServer.Application.Features.AuthMessageses.Queries.ListDynamic;
using IdentityServer.Application.Features.AuthMessageses.Queries.GetById;
using IdentityServer.Domain.Entities;

namespace IdentityServer.Application.Features.AuthMessageses.Profiles;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        
		CreateMap<BulkCreateAuthMessagesCommand,AuthMessages>();
		CreateMap<AuthMessages, BulkCreateAuthMessagesResponse>();
		CreateMap<CreateAuthMessagesCommand,AuthMessages>();
		CreateMap<AuthMessages, CreateAuthMessagesResponse>();
		CreateMap<UpdateAuthMessagesCommand,AuthMessages>();
		CreateMap<AuthMessages, UpdateAuthMessagesResponse>();
		CreateMap<BulkUpdateAuthMessagesCommand,AuthMessages>();
		CreateMap<AuthMessages, BulkUpdateAuthMessagesResponse>();
		CreateMap<DeleteByIdAuthMessagesCommand,AuthMessages>();
		CreateMap<AuthMessages, DeleteByIdAuthMessagesResponse>();
		CreateMap<Paginate<AuthMessages>, ListModel<ListDynamicAuthMessagesResponse>>();
		CreateMap<AuthMessages, ListDynamicAuthMessagesResponse>();
		CreateMap<AuthMessages, GetByIdAuthMessagesResponse>();
    }
}




