
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

namespace Jumper.Application.Features.EntityPropertyFeatureDefinitionProjectEntityPropertyRelations.Commands.BulkCreate;

public class BulkCreateEntityPropertyFeatureDefinitionProjectEntityPropertyRelationResponse
{
    
	public Guid Id { get; set; }
	public Guid EntityPropertyFeatureDefinitionId { get; set; }
	public Guid ProjectEntityPropertyId { get; set; }
	public DateTime CreatedTime { get; set; }
	public DateTime? UpdatedTime { get; set; }
	public DateTime? DeletedTime { get; set; }
    
}




