



//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Core.Persistence.Models.Responses;
using Core.Persistence.Paging;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.BulkCreate;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.Create;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.Update;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.BulkUpdate;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Commands.DeleteById;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Queries.ListDynamic;
using Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Queries.GetById;
using Jumper.Domain.Entities;

namespace Jumper.Application.Features.EntityFeatureDefinitionProjectEntityRelations.Profiles;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        
		CreateMap<BulkCreateEntityFeatureDefinitionProjectEntityRelationCommand,EntityFeatureDefinitionProjectEntityRelation>();
		CreateMap<EntityFeatureDefinitionProjectEntityRelation, BulkCreateEntityFeatureDefinitionProjectEntityRelationResponse>();
		CreateMap<CreateEntityFeatureDefinitionProjectEntityRelationCommand,EntityFeatureDefinitionProjectEntityRelation>();
		CreateMap<EntityFeatureDefinitionProjectEntityRelation, CreateEntityFeatureDefinitionProjectEntityRelationResponse>();
		CreateMap<UpdateEntityFeatureDefinitionProjectEntityRelationCommand,EntityFeatureDefinitionProjectEntityRelation>();
		CreateMap<EntityFeatureDefinitionProjectEntityRelation, UpdateEntityFeatureDefinitionProjectEntityRelationResponse>();
		CreateMap<BulkUpdateEntityFeatureDefinitionProjectEntityRelationCommand,EntityFeatureDefinitionProjectEntityRelation>();
		CreateMap<EntityFeatureDefinitionProjectEntityRelation, BulkUpdateEntityFeatureDefinitionProjectEntityRelationResponse>();
		CreateMap<DeleteByIdEntityFeatureDefinitionProjectEntityRelationCommand,EntityFeatureDefinitionProjectEntityRelation>();
		CreateMap<EntityFeatureDefinitionProjectEntityRelation, DeleteByIdEntityFeatureDefinitionProjectEntityRelationResponse>();
		CreateMap<Paginate<EntityFeatureDefinitionProjectEntityRelation>, ListModel<ListDynamicEntityFeatureDefinitionProjectEntityRelationResponse>>();
		CreateMap<EntityFeatureDefinitionProjectEntityRelation, ListDynamicEntityFeatureDefinitionProjectEntityRelationResponse>();
		CreateMap<EntityFeatureDefinitionProjectEntityRelation, GetByIdEntityFeatureDefinitionProjectEntityRelationResponse>();
    }
}




