
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using Core.ApiHelpers.JwtHelper.Models;
using IdentityServer.Application.Base;

namespace IdentityServer.Application.Features.ApiResourceScopes.Rules;

public class ApiResourceScopeBusinessRules : BaseBusinessRules
{

    public ApiResourceScopeBusinessRules(TokenParameters tokenParameters) : base(tokenParameters)
    {
    }
}



