
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityFeatureDefinitions.Queries.GetById;
using Jumper.Application.Features.EntityFeatureDefinitions.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using MediatR;
namespace Jumper.Application.Features.EntityFeatureDefinitions.Handlers.Queries.GetById;

public class GetByIdEntityFeatureDefinitionQueryHandler : IRequestHandler<GetByIdEntityFeatureDefinitionQuery, GetByIdEntityFeatureDefinitionResponse>
{
    private readonly IEntityFeatureDefinitionDal _entityFeatureDefinitionDal;
    private readonly EntityFeatureDefinitionBusinessRules _entityFeatureDefinitionBusinessRules;
    private readonly IMapper _mapper;

    public GetByIdEntityFeatureDefinitionQueryHandler(IMapper mapper, IEntityFeatureDefinitionDal entityFeatureDefinitionDal, EntityFeatureDefinitionBusinessRules entityFeatureDefinitionBusinessRules)
    {
        _mapper = mapper;
        _entityFeatureDefinitionDal = entityFeatureDefinitionDal;
        _entityFeatureDefinitionBusinessRules = entityFeatureDefinitionBusinessRules;
    }

    public async Task<GetByIdEntityFeatureDefinitionResponse> Handle(GetByIdEntityFeatureDefinitionQuery request, CancellationToken cancellationToken)
    {
        
        var data = await _entityFeatureDefinitionDal.GetAsync(w => w.Id == request.Id, cancellationToken : cancellationToken);
            
        await _entityFeatureDefinitionBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        return _mapper.Map<GetByIdEntityFeatureDefinitionResponse>(data);
    }
}



