
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using AutoMapper;
using IdentityServer.Application.Features.Clients.Queries.GetById;
using IdentityServer.Application.Features.Clients.Rules;
using IdentityServer.Application.Services.Repositories;
using IdentityServer.Domain.Entities;
using MediatR;
namespace IdentityServer.Application.Features.Clients.Handlers.Queries.GetById;

public class GetByIdClientQueryHandler : IRequestHandler<GetByIdClientQuery, GetByIdClientResponse>
{
    private readonly IClientDal _clientDal;
    private readonly ClientBusinessRules _clientBusinessRules;
    private readonly IMapper _mapper;

    public GetByIdClientQueryHandler(IMapper mapper, IClientDal clientDal, ClientBusinessRules clientBusinessRules)
    {
        _mapper = mapper;
        _clientDal = clientDal;
        _clientBusinessRules = clientBusinessRules;
    }

    public async Task<GetByIdClientResponse> Handle(GetByIdClientQuery request, CancellationToken cancellationToken)
    {
        
        var data = await _clientDal.GetAsync(w => w.Id == request.Id, cancellationToken : cancellationToken);
            
        _clientBusinessRules.ThrowExceptionIfDataNull(data);

        //İş Kurallarınızı Burada Çağırabilirsiniz.

        return _mapper.Map<GetByIdClientResponse>(data);
    }
}



