
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 29.10.2023 12:13
//---------------------------------------------------------------------------------------

using AutoMapper;
using Jumper.Application.Features.EntityFeatureDefinitions.Commands.Create;
using Jumper.Application.Features.EntityFeatureDefinitions.Rules;
using Jumper.Application.Services.Repositories;
using Jumper.Domain.Entities;
using MediatR;
namespace Jumper.Application.Features.EntityFeatureDefinitions.Handlers.Commands.Create;

public class CreateEntityFeatureDefinitionCommandHandler : IRequestHandler<CreateEntityFeatureDefinitionCommand, CreateEntityFeatureDefinitionResponse>
{
    private readonly IEntityFeatureDefinitionDal _entityFeatureDefinitionDal;
    private readonly EntityFeatureDefinitionBusinessRules _entityFeatureDefinitionBusinessRules;
    private readonly IMapper _mapper;

    public CreateEntityFeatureDefinitionCommandHandler(IMapper mapper, IEntityFeatureDefinitionDal entityFeatureDefinitionDal, EntityFeatureDefinitionBusinessRules entityFeatureDefinitionBusinessRules)
    {
        _mapper = mapper;
        _entityFeatureDefinitionDal = entityFeatureDefinitionDal;
        _entityFeatureDefinitionBusinessRules = entityFeatureDefinitionBusinessRules;
    }

    public async Task<CreateEntityFeatureDefinitionResponse> Handle(CreateEntityFeatureDefinitionCommand request, CancellationToken cancellationToken)
    {
        var data = _mapper.Map<EntityFeatureDefinition>(request);

        
        //İş Kurallarınızı Burada Çağırabilirsiniz.

        await _entityFeatureDefinitionDal.AddAsync(data);

        return _mapper.Map<CreateEntityFeatureDefinitionResponse>(data);
    }
}



