
//---------------------------------------------------------------------------------------
//      This code was generated by a Jumper tool. 
//      Runtime version : 1.0
//      Generation Time : 23.10.2023 11:28
//---------------------------------------------------------------------------------------

using MediatR;

namespace IdentityServer.Application.Features.ClientUserRelations.Commands.Update;

public class UpdateClientUserRelationCommand : IRequest<UpdateClientUserRelationResponse>  
{
    
	public Guid ClientId { get; set; }
	public Guid Id { get; set; }
	public Guid UserId { get; set; }
    
}




